export const AvailableLanguages: { [key: string]: string } = {
  en: 'English',
  'zh-CN': '简体中文',
  'zh-TW': '正體中文',
};

/*
export const TransTable: {[key: string]: {[key: string]: string}} = {
  en: {
    main_subtitle: 'Share your images. Optimized for web.',
    main_register: 'Register',
    main_login: 'Login',
    language_switch: 'Switch Language',

    header_admin: 'Admin area',
    header_upload: 'Upload',
    header_upload_frozen: 'Your account is suspended.',
    header_change_avatar: 'Change avatar',
    header_change_password: 'Change Password',
    header_logout: 'Logout',
    header_image_pref: 'Image preference',
    header_gallery: 'Gallery',

    login_title: 'Login',
    login_username: 'Username',
    login_password: 'Password',
    login_action_login: 'Login',
    login_action_register: 'Register account',
    login_success_message: 'Login successful.',
    login_failed_message: 'Login failed: %1.',

    register_title: 'Register',
    register_username: 'Username',
    register_password: 'Password',
    register_password_repeat: 'Repeat password',
    register_password_see: 'Unmask password',
    register_password_hide: 'Mask password',
    register_code: 'Invite code',
    register_hint_password: 'At least 8 characters, contains upper, lower letter and number',
    register_error_user_exist: 'User already exist',
    register_error_password_weak: 'Password too weak',
    register_error_password_mismatch: 'Passwords didn\'t match',
    register_action_login: 'I have account',
    register_action_register: 'Register',

    guard_need_login_message: 'You must login to access this page.',

    gallery_broken_image: 'Image not available',
    gallery_loading: 'Loading...',
    gallery_tag_search: 'Show specified tag only...',
    gallery_tag_placeholder: 'Input tag here',
    gallery_tag_failed_message: 'Failed loading tags: %1.',
    gallery_tag_empty: '(Empty tag)',
    gallery_group_label: 'Group images by: ',
    gallery_group_time: 'Time',
    gallery_group_tag: 'Tag',
    gallery_group_time_label: 'Time span: ',
    gallery_group_time_day: 'Day',
    gallery_group_time_week: 'Week',
    gallery_group_time_month: 'Month',
    gallery_group_time_year: 'Year',
    gallery_select_all_typed: 'Select all of this group',
    gallery_deselect_all_typed: 'Deselect all of this group',
    gallery_reverse_all_typed: 'Reverse select images of this group',
    gallery_action_edit: 'Edit selected images',
    gallery_action_code: 'Get code of selected images to publish',
    gallery_action_delete: 'Delete selected images',
    gallery_action_select_all: 'Select all images',
    gallery_action_select_reverse: 'Reverse selection',
    gallery_action_done: 'Done',
    gallery_overlay_action_info: 'Image info',
    gallery_overlay_action_open: 'Open image file in new page',
    gallery_overlay_action_edit: 'Edit this image',
    gallery_overlay_action_code: 'Get code of this image to publish',
    gallery_overlay_action_delete: 'Delete this image',
    gallery_overlay_action_close: 'Return to gallery',
    gallery_fetch_failed: 'Failed loading images: %1.',
    gallery_empty: 'Your gallery is empty.',
    gallery_empty_other: 'Nothing here.',
    gallery_empty_upload: 'Upload image',

    upload_minimize: 'Minimize',
    upload_expand: 'Expand',
    upload_close: 'Close',
    upload_title_file_plural_0: 'no file',
    upload_title_file_plural_1: '1 file',
    upload_title_file_plural_other: 'files',
    upload_title_idle: 'Upload',
    upload_title_select_files_p1: '',
    upload_title_select_files_p2: 'selected for upload',
    upload_title_uploading_fine_p1: 'Uploading files,',
    upload_title_uploading_fine_p2: ', ',
    upload_title_uploading_fine_p3: 'finished',
    upload_title_uploading_some_error_p1: 'Uploading files,',
    upload_title_uploading_some_error_p2: ',',
    upload_title_uploading_some_error_p3: 'finished,',
    upload_title_uploading_some_error_p4: 'failed',
    upload_title_uploaded_fine: 'Upload finished, all files succeed',
    upload_title_uploaded_some_error_p1: 'Upload finished,',
    upload_title_uploaded_some_error_p2: 'succeed,',
    upload_title_uploaded_some_error_p3: 'failed',
    upload_drop_file_pre: 'Drop image files here, or ',
    upload_drop_file_picker: 'Select files',
    upload_drop_file_post: '.',
    upload_drop_file_release: 'Release your mouse to submit files.',
    upload_file_name_unknown: '(Unknown filename)',
    upload_file_type_unknown: '(Unknown type)',
    upload_submit_no_valid: 'No valid image file found in your selected files.',
    upload_preview_type_header: 'Display mode: ',
    upload_preview_type_grid: 'Grid',
    upload_preview_type_list: 'List',
    upload_preview_limit_height: 'Limit height',
    upload_preview_title: 'Image Preview',
    upload_info_form_title: 'Settings',
    upload_info_tag_header: 'Tag for images',
    upload_info_tag_header_help: 'Tag is the primary way to group your images',
    upload_info_tag_header_placeholder: 'Type tag here, or keep blank to use empty tag',
    upload_info_tag_header_hint: '(Default: tag will set to your input)',
    upload_info_allow_origins: 'Allow origins',
    upload_info_allow_origins_help: 'User can only access images from these sites',
    upload_info_allow_origins_placeholder: 'Type domain here, split with comma or enter',
    upload_info_allow_origins_any: ' (Any site)',
    upload_info_allow_origins_none: ' (Direct access)',
    upload_info_allow_origins_exact: ' (Exact match)',
    upload_info_allow_origins_wildcard: ' (Wildcard match)',
    upload_info_allow_origins_bad: ' (Current input is not a valid domain)',
    upload_info_allow_origins_exist: ' (Already covered)',
    upload_failed_info: 'Upload failed: %1',
    upload_operation_reset: 'Reset',
    upload_operation_submit: 'Upload',

    upload_advanced_button: 'Advanced upload',
    upload_advanced_title: 'Advanced upload',
    upload_advanced_warning_head: 'Warning: ',
    upload_advanced_warning_text: 'Advanced upload allows you to upload files in different formats of the same image,' +
      ' and serve to the user as is. Server will not do any check, even not checking if it is a valid image file,' +
      ' so as it called "Advanced". Please be cautious.',
    upload_advanced_file_title: 'Pick files',
    upload_advanced_select_file: 'Select file',
    upload_advanced_selected: 'Reselect',
    upload_advanced_status_not_selected: 'Not selected',
    upload_advanced_status_before: 'File size:',
    upload_advanced_status_after: '.',
    upload_advanced_info_title: 'Settings',
    upload_advanced_operation_cancel: 'Cancel',
    upload_advanced_operation_upload: 'Upload',
    upload_advanced_operation_uploading: 'Uploading',
    upload_advanced_operation_uploaded: 'Close',
    upload_advanced_operation_exit: 'Exit',
    upload_advanced_failed_message: 'Uploading file failed: %1.',
    upload_advanced_success_message: 'Upload successful.',
    upload_advanced_progress: 'Upload Progress',

    edit_images_title: 'Edit images',
    edit_images_tab_tag: 'Tag',
    edit_images_title_tag: 'Change tag of images',
    edit_images_tab_origins: 'Origins',
    edit_images_title_origins: 'Change origins of images',

    edit_images_result_success: 'Image edit successful.',
    edit_images_result_failed: 'Image edit failed: %1.',

    dialog_cancel: 'Cancel',
    dialog_submit: 'OK',

    default_confirm_title: 'Confirmation',
    default_confirm_word: 'Are you sure to process?',
    default_confirm_yes: 'Confirm',
    default_confirm_no: 'Cancel',

    delete_select_confirm_title: 'Delete images',
    delete_select_confirm_word: 'Are you sure to delete selected images?',
    delete_select_confirm_yes: 'Delete',
    delete_select_confirm_no: 'Cancel',

    delete_this_confirm_title: 'Delete this image',
    delete_this_confirm_word: 'Are you sure to delete this image?',
    delete_this_confirm_yes: 'Delete',
    delete_this_confirm_no: 'Cancel',

    upload_confirm_title: 'Abort upload and exit',
    upload_confirm_word: 'Are you sure to exit? Some files may not be uploaded if you exit now.',
    upload_confirm_yes: 'Exit',
    upload_confirm_no: 'Cancel',

    delete_images_result_success: 'Image deleted.',
    delete_images_result_failed: 'Image delete failed: %1.',

    generate_code_title: 'Generate Code for Publish',
    generate_code_type: 'Code type:',
    generate_code_type_label: 'Select a code type',
    generate_type_html: 'HTML',
    generate_type_bbcode: 'BBCode',
    generate_type_url: 'URL',
    generate_type_custom: 'Customize',
    generate_custom_template: 'Template',
    generate_custom_template_placeholder: 'Template code for each image',
    generate_custom_template_hint: 'Use %url% to mark the position to place url',
    generate_custom_separator: 'Separator',
    generate_custom_separator_placeholder: 'Separator code between images',
    generate_custom_separator_hint: 'Separator code will be placed between codes of each image',
    generate_result_copy: 'Copy',
    generate_result_copied: 'Code copied.',
    generate_code_done: 'Done',
    generate_sort_title: 'Sort images',
    generate_sort_reverse: 'Reverse',

    info_title: 'Image info',
    info_user: 'Uploader',
    info_tag: 'Image tag',
    info_upload_time: 'Upload time',
    info_view: 'View count',
    info_origins: 'Allowed origin sites',
    info_formats: 'Available formats',
    info_formats_available: 'This format is available',
    info_formats_encoding: 'This format is being transcode, and will be available soon',
    info_done: 'Close',

    change_password_title: 'Change Password',
    change_password_old: 'Old password',
    change_password_new: 'New password',
    change_password_cancel: 'Cancel',
    change_password_submit: 'Change',
    change_password_failed: 'Change password failed: %1.',
    change_password_succeed: 'Password changed. Please re-login.',

    change_avatar_title: 'Change Avatar',
    change_avatar_title_pick_file: '1. Pick an image',
    change_avatar_file_selector: 'Select image',
    change_avatar_file_bad: 'Failed loading image. Is this a valid image file?',
    change_avatar_title_crop: '2. Crop your image',
    change_avatar_preview_no_file: 'Please select an image first.',
    change_avatar_preview: 'Avatar preview',
    change_avatar_success: 'Avatar changed.',
    change_avatar_failed: 'Failed change avatar: %1',
    change_avatar_cancel: 'Cancel',
    change_avatar_submit: 'Save',

    admin_user: 'User',
    admin_code: 'Code',
    admin_user_search: 'Show users name contains keyword only...',
    admin_user_search_placeholder: 'Input keyword here',
    admin_user_fetch_failed: 'Failed fetching user list: %1.',
    admin_user_username: 'User',
    admin_user_privileged: 'Privileged',
    admin_user_privileged_set: 'User privilege status changed.',
    admin_user_privileged_failed: 'Failed changing user privilege status: %1.',
    admin_user_frozen: 'Frozen',
    admin_user_frozen_set: 'User freeze status changed.',
    admin_user_frozen_failed: 'Failed changing user freeze status: %1.',
    admin_operation: 'Operations',
    admin_user_set_password: 'Set Password',
    admin_user_password_ok: 'User password changed.',
    admin_user_password_failed: 'Failed changing user password: %1.',
    admin_user_set_avatar: 'Set Avatar',
    admin_user_check_gallery: 'Check Gallery',
    admin_delete: 'Delete',
    admin_user_delete_ok: 'User deleted.',
    admin_user_delete_failed: 'Failed deleting user: %1.',
    admin_user_delete_selected: 'Delete selected users',
    admin_user_delete_selected_ok: 'Selected users deleted.',
    admin_user_delete_selected_failed: 'Failed deleting selected users: %1.',
    admin_user_add: 'Add user',
    admin_code_code: 'Invite code',
    admin_code_times: 'Available times',
    admin_code_set_times: 'Set available times',
    admin_code_delete_selected: 'Delete selected codes',
    admin_code_add: 'Add invite code',
    admin_code_fetch_failed: 'Failed fetching invite code list: %1.',
    admin_code_delete_ok: 'Invite code deleted.',
    admin_code_delete_failed: 'Failed deleting invite code: %1.',
    admin_times_set_ok: 'Available times updated.',
    admin_times_set_failed: 'Failed updating available times: %1.',

    paginator_first_page: 'First page',
    paginator_last_page: 'Last page',
    paginator_previous_page: 'Previous page',
    paginator_next_page: 'Next page',
    paginator_per_page: 'Items per page: ',
    paginator_position_none: 'No item',
    paginator_position_zero: '0, total %1',
    paginator_position: '%1 – %2 of %3',

    default_prompt_title: 'Input a value',
    default_prompt_label: 'The value',
    default_prompt_placeholder: 'Input value here',
    default_prompt_yes: 'Submit',
    default_prompt_no: 'Cancel',

    set_password_prompt_title: 'Set user password',
    set_password_prompt_label: 'New Password',
    set_password_prompt_placeholder: 'Input new password here',
    set_password_prompt_yes: 'Set',
    set_password_prompt_no: 'Cancel',

    delete_user_confirm_title: 'Delete user',
    delete_user_confirm_word: 'Are you sure to delete this user?',
    delete_user_confirm_yes: 'Delete',
    delete_user_confirm_no: 'Cancel',

    delete_users_confirm_title: 'Delete selected users',
    delete_users_confirm_word: 'Are you sure to delete selected users?',
    delete_users_confirm_yes: 'Delete',
    delete_users_confirm_no: 'Cancel',

    default_choice_title: 'Select one value',
    default_choice_word: 'Please select one of the two values',
    default_choice_right: 'Right',
    default_choice_left: 'Left',

    delete_user_choice_title: 'Image handling',
    delete_user_choice_word: 'How to handle images (if any) of this user?',
    delete_user_choice_right: 'Adopt',
    delete_user_choice_left: 'Delete',

    delete_users_choice_title: 'Image handling',
    delete_users_choice_word: 'How to handle images (if any) of the selected users?',
    delete_users_choice_right: 'Adopt',
    delete_users_choice_left: 'Delete',

    add_user_title: 'Add user',
    add_user_username: 'Username',
    add_user_password: 'Password',
    add_user_privileged: 'Privilege this user',
    add_user_error_user_exist: 'User already exist',
    add_user_cancel: 'Cancel',
    add_user_submit: 'Add',
    add_user_success_msg: 'User %1 added.',
    add_user_error_msg: 'Failed adding user: %1.',

    add_code_title: 'Add invite code',
    add_code_code: 'Code token',
    add_code_times: 'Available times',
    add_code_error_code_exist: 'Code already exist',
    add_code_cancel: 'Cancel',
    add_code_submit: 'Add',
    add_code_success_msg: 'Code %1 added.',
    add_code_error_msg: 'Failed adding code: %1.',

    code_times_prompt_title: 'Set available times',
    code_times_prompt_label: 'Available times',
    code_times_prompt_placeholder: 'Input a number here',
    code_times_prompt_yes: 'Save',
    code_times_prompt_no: 'Cancel',

    delete_code_confirm_title: 'Delete code',
    delete_code_confirm_word: 'Are you sure to delete this code?',
    delete_code_confirm_yes: 'Delete',
    delete_code_confirm_no: 'Cancel',

    not_found_title: 'Not found',
    not_found_word: 'Nothing available here.',
    not_found_back: 'To main page',

    format_pref_title: 'Format preference settings',
    format_pref_note_title: 'Note: ',
    format_pref_note_content: 'Here you can set your image format preference. By default we serve you image in the format' +
      ' that has minimal size while supported by your browser, and this means CPU will do more work to decode the image.' +
      ' Usually the difference is small, but smaller file loads significantly faster, so we recommend you to keep the default.' +
      ' However, if you are using a low-end device or you really cares battery life, you can manually set your preference below,' +
      ' and we will respect your settings and try to serve you images with formats in your desired order.',
    format_pref_support_status: 'Your browser\'s support to different formats: ',
    format_pref_support_status_detecting: 'Detecting...',
    format_pref_support_status_supported: 'Supported',
    format_pref_support_status_not_supported: 'Not supported',
    format_pref_support_status_jpeg_png: 'Every browser supports PNG and JPEG.',
    format_pref_drag_hint: 'Drag to sort the formats:',
    format_pref_cancel: 'Cancel',
    format_pref_reset: 'Reset',
    format_pref_save: 'Save',
    format_pref_save_done: 'Preference saved.',
    format_pref_reset_done: 'Preference cleared.',

    about_title: 'About',
    about_content: 'Chromatic is an image store platform specially targeted on optimizing web access experience.',
    about_privacy: 'Privacy',
    about_privacy_content: 'We value your privacy, and collects only necessary data. We do anonymous count when you are requesting images' +
      ' from us, and the data is solely used to decide if we should put more resource to optimize load experience. If you set the' +
      ' format preference, then a cookie will be sent everytime you request images from us (include from other sites), to let us know' +
      ' your preference. We won\'t use the cookie to do any other thing.',
    about_based_on: 'Credits',
    about_based_content: 'Chromatic is made possible by many open source projects.',
    about_license_other: 'Other',

    info_main: 'Main Page',
    info_about: 'About',

    title_about: 'About',
    title_admin: 'Admin',
    title_gallery: 'Gallery',
    title_gallery_me: 'My gallery',
    title_login: 'Login',
    title_register: 'Register',
    title_not_found: 'Not Found',
    title_upload: 'Upload',
    title_uploading: 'Uploading, %1 files finished',
    title_uploading_error: 'Uploading, %1 files finished, %2 files failed',
    title_uploaded: '%1 files uploaded',
    title_uploaded_error: '%1 files uploaded, %2 files failed',

    time_year: 'y',
    time_year_post: 'Year %1',
    time_month: 'MMM, y',
    time_month_post: '%1',
    time_week: 'w, y',
    time_week_post: 'Week %1',
    time_day: 'mediumDate',
    time_day_post: '%1',

    '0000': 'Successful',
    '0001': 'Password strength too weak',
    '0002': 'User already exist',
    '0003': 'The invite code is invalid',
    '0004': 'Wrong account or password',
    '0005': 'The specified user doesn\'t exist',
    '0006': 'The specified invite code already exist',
    '0007': 'The specified invite code doesn\'t exist',
    '0008': 'Bad request',
    '0009': 'The specified image doesn\'t exist',
    '0010': 'The image is broken or unsupported',
    '0011': 'Failed encoding image',
    '0012': 'Original image doesn\'t exist',
    '0013': 'Request being made without credential',
    '0014': 'Credential used in request has expired',
    '0015': 'Permission denied',

    9999: 'Unknown error',

    http_error: 'HTTP %1',
    net_error: 'Network error',
    action_retry: 'Retry',
    login_expired: 'Your login info has expired and you have to login.',
    other: '(!Missing!)'
  },
  'zh-CN': {
    main_subtitle: '分享你的图片。为Web访问优化。',
    main_register: '注册',
    main_login: '登录',
    language_switch: '切换语言',

    header_admin: '管理界面',
    header_upload: '上传',
    header_upload_frozen: '你的账号已被停用。',
    header_change_avatar: '更换头像',
    header_change_password: '更改密码',
    header_logout: '退出登录',
    header_image_pref: '图像格式偏好',
    header_gallery: '图片库',

    login_title: '登录',
    login_username: '用户名',
    login_password: '密码',
    login_action_login: '登录',
    login_action_register: '注册新帐号',
    login_success_message: '登录成功。',
    login_failed_message: '登录失败：%1。',

    register_title: '注册',
    register_username: '用户名',
    register_password: '密码',
    register_password_repeat: '重复密码',
    register_password_see: '显示密码',
    register_password_hide: '隐藏密码',
    register_code: '邀请码',
    register_hint_password: '密码至少8位长，须同时包含数字及大小写字母',
    register_error_user_exist: '用户已经存在',
    register_error_password_weak: '密码强度太弱',
    register_error_password_mismatch: '两次输入的密码不一致',
    register_action_login: '登录已有帐号',
    register_action_register: '注册',

    guard_need_login_message: '你必须登录才可浏览此界面。',

    gallery_broken_image: '图片不可用',
    gallery_loading: '正在加载……',
    gallery_tag_search: '仅显示特定标签的图片',
    gallery_tag_placeholder: '输入标签',
    gallery_tag_failed_message: '标签加载失败：%1。',
    gallery_tag_empty: '（空标签）',
    gallery_group_label: '分组依据：',
    gallery_group_time: '时间',
    gallery_group_tag: '标签',
    gallery_group_time_label: '分组时长：',
    gallery_group_time_day: '天',
    gallery_group_time_week: '周',
    gallery_group_time_month: '月',
    gallery_group_time_year: '年',
    gallery_select_all_typed: '全选本组',
    gallery_deselect_all_typed: '取消选择本组',
    gallery_reverse_all_typed: '反选本组',
    gallery_action_edit: '编辑所选图片',
    gallery_action_code: '获取所选图片的发布代码',
    gallery_action_delete: '删除所选图片',
    gallery_action_select_all: '选择当前所有图片',
    gallery_action_select_reverse: '反选所有图片',
    gallery_action_done: '完成',
    gallery_overlay_action_info: '图片信息',
    gallery_overlay_action_open: '在新标签页内打开图片',
    gallery_overlay_action_edit: '编辑此图片信息',
    gallery_overlay_action_code: '获取此图片的发布代码',
    gallery_overlay_action_delete: '删除此图片',
    gallery_overlay_action_close: '回到列表',
    gallery_fetch_failed: '图片列表加载失败：%1。',
    gallery_empty: '你还没有上传图片。',
    gallery_empty_other: '无图片。',
    gallery_empty_upload: '上传',

    upload_minimize: '最小化',
    upload_expand: '还原',
    upload_close: '关闭',
    upload_title_file_plural_0: '尚无文件',
    upload_title_file_plural_1: '1个文件',
    upload_title_file_plural_other: '个文件',
    upload_title_idle: '上传',
    upload_title_select_files_p1: '已选择',
    upload_title_select_files_p2: '',
    upload_title_uploading_fine_p1: '正在上传，',
    upload_title_uploading_fine_p2: '，',
    upload_title_uploading_fine_p3: '已上传完毕。',
    upload_title_uploading_some_error_p1: '正在上传，',
    upload_title_uploading_some_error_p2: '，',
    upload_title_uploading_some_error_p3: '已上传完毕，',
    upload_title_uploading_some_error_p4: '上传失败。',
    upload_title_uploaded_fine: '上传完毕，全部文件上传成功。',
    upload_title_uploaded_some_error_p1: '上传完毕，',
    upload_title_uploaded_some_error_p2: '上传成功，',
    upload_title_uploaded_some_error_p3: '上传失败。',
    upload_drop_file_pre: '将文件拖拽到此处，或',
    upload_drop_file_picker: '选择文件',
    upload_drop_file_post: '以上传。',
    upload_drop_file_release: '松开鼠标即可上传',
    upload_file_name_unknown: '（未知文件名）',
    upload_file_type_unknown: '（未知格式）',
    upload_submit_no_valid: '你选择的文件里没有图片。',
    upload_preview_type_header: '显示模式：',
    upload_preview_type_grid: '网格',
    upload_preview_type_list: '列表',
    upload_preview_limit_height: '限制预览高度',
    upload_preview_title: '图片预览',
    upload_info_form_title: '设置',
    upload_info_tag_header: '图片标签',
    upload_info_tag_header_help: '标签是用来归类图像的主要方式',
    upload_info_tag_header_placeholder: '在此输入标签，或留空以使用空标签',
    upload_info_tag_header_hint: '（默认：创建新标签）',
    upload_info_allow_origins: '可访问网站',
    upload_info_allow_origins_help: '浏览者仅能从这些网站访问你的图片',
    upload_info_allow_origins_placeholder: '在此输入域名，使用逗号或回车分隔',
    upload_info_allow_origins_any: '（任何网站）',
    upload_info_allow_origins_none: '（直接打开）',
    upload_info_allow_origins_exact: '（精确匹配）',
    upload_info_allow_origins_wildcard: '（允许子站）',
    upload_info_allow_origins_bad: '（当前输入不是一个有效域名）',
    upload_info_allow_origins_exist: '（允许列表已包含此域名）',
    upload_failed_info: '上传失败：%1',
    upload_operation_reset: '重置',
    upload_operation_submit: '上传',

    upload_advanced_button: '高级上传',
    upload_advanced_title: '高级上传',
    upload_advanced_warning_head: '警告：',
    upload_advanced_warning_text: '高级上传允许你手动上传不同格式的同一张图片，并直接将上传的文件提供给用户。' +
      '服务端不会对上传的文件进行任何校验，因此本功能仅面向高级用户。在操作时请小心。',
    upload_advanced_file_title: '上传文件',
    upload_advanced_select_file: '选择文件',
    upload_advanced_selected: '重新选择',
    upload_advanced_status_not_selected: '尚未选择文件',
    upload_advanced_status_before: '文件大小：',
    upload_advanced_status_after: '。',
    upload_advanced_info_title: '设置',
    upload_advanced_operation_cancel: '取消',
    upload_advanced_operation_upload: '上传',
    upload_advanced_operation_uploading: '正在上传',
    upload_advanced_operation_uploaded: '关闭',
    upload_advanced_operation_exit: '退出',
    upload_advanced_failed_message: '上传失败： %1。',
    upload_advanced_success_message: '上传成功',
    upload_advanced_progress: '上传进度',

    edit_images_title: '编辑图片',
    edit_images_tab_tag: '标签',
    edit_images_title_tag: '更改图片标签',
    edit_images_tab_origins: '可访问网站',
    edit_images_title_origins: '更改图片可访问网站',

    edit_images_result_success: '图片编辑成功。',
    edit_images_result_failed: '图片编辑失败：%1。',

    dialog_cancel: '取消',
    dialog_submit: '确定',

    default_confirm_title: '确认',
    default_confirm_word: '确实要执行动作吗？',
    default_confirm_yes: '确定',
    default_confirm_no: '取消',

    delete_select_confirm_title: '删除图片',
    delete_select_confirm_word: '确实要删除选择的图片吗？',
    delete_select_confirm_yes: '删除',
    delete_select_confirm_no: '取消',

    delete_this_confirm_title: '删除此图片',
    delete_this_confirm_word: '确实要删除这张图片吗？',
    delete_this_confirm_yes: '删除',
    delete_this_confirm_no: '取消',

    upload_confirm_title: '中止上传并退出',
    upload_confirm_word: '确实要退出吗？部分文件可能不会被上传。',
    upload_confirm_yes: '退出',
    upload_confirm_no: '取消',

    delete_images_result_success: '图片已删除。',
    delete_images_result_failed: '图片删除失败：%1。',

    generate_code_title: '生成发布代码',
    generate_code_type: '代码类型',
    generate_code_type_label: '选择一个代码类型',
    generate_type_html: 'HTML',
    generate_type_bbcode: 'BBCode',
    generate_type_url: '链接',
    generate_type_custom: '自定义',
    generate_custom_template: '模板',
    generate_custom_template_placeholder: '每张图片的代码模板',
    generate_custom_template_hint: '请使用%url%标注放置图片链接的位置',
    generate_custom_separator: '分隔内容',
    generate_custom_separator_placeholder: '置于图片间的代码',
    generate_custom_separator_hint: '分隔代码将置于每两张图片代码的中间',
    generate_result_copy: '复制',
    generate_result_copied: '代码已复制',
    generate_code_done: '完成',
    generate_sort_title: '排序图片',
    generate_sort_reverse: '反序',

    info_title: '图片信息',
    info_user: '所有者',
    info_tag: '标签',
    info_upload_time: '上传时间',
    info_view: '浏览量',
    info_origins: '允许访问的站点',
    info_formats: '可用格式',
    info_formats_available: '此格式可用',
    info_formats_encoding: '此格式正在转码，即将可用',
    info_done: '关闭',

    change_password_title: '更改密码',
    change_password_old: '旧密码',
    change_password_new: '新密码',
    change_password_cancel: '取消',
    change_password_submit: '更改',
    change_password_failed: '更改密码失败：%1。',
    change_password_succeed: '密码已更改。请重新登录。',

    change_avatar_title: '更换头像',
    change_avatar_title_pick_file: '第一步：请选择一张图片',
    change_avatar_file_selector: '选择图片',
    change_avatar_file_bad: '图片加载失败。请确认这是一个图片文件。',
    change_avatar_title_crop: '第二步：裁剪图片',
    change_avatar_preview_no_file: '请先选择一张图片，进行裁剪。',
    change_avatar_preview: '头像预览',
    change_avatar_success: '头像已更换。',
    change_avatar_failed: '头像更换失败：%1',
    change_avatar_cancel: '取消',
    change_avatar_submit: '保存',

    admin_user: '用户',
    admin_code: '邀请码',
    admin_user_search: '仅显示用户名包含关键字的用户',
    admin_user_search_placeholder: '输入关键字',
    admin_user_fetch_failed: '用户列表获取失败：%1。',
    admin_user_username: '用户名',
    admin_user_privileged: '高级功能权限',
    admin_user_privileged_set: '已修改用户权限。',
    admin_user_privileged_failed: '用户权限修改失败：%1。',
    admin_user_frozen: '冻结',
    admin_user_frozen_set: '已修改用户冻结状态。',
    admin_user_frozen_failed: '用户冻结状态修改失败：%1。',
    admin_operation: '操作',
    admin_user_set_password: '设置密码',
    admin_user_password_ok: '密码已修改。',
    admin_user_password_failed: '密码修改失败：%1。',
    admin_user_set_avatar: '设置头像',
    admin_user_check_gallery: '查看用户图片库',
    admin_delete: '删除',
    admin_user_delete_ok: '用户已删除。',
    admin_user_delete_failed: '用户删除失败：%1。',
    admin_user_delete_selected: '删除已选用户',
    admin_user_delete_selected_ok: '所选用户已删除。',
    admin_user_delete_selected_failed: '所选用户删除失败：%1。',
    admin_user_add: '添加用户',
    admin_code_code: '邀请码',
    admin_code_times: '可用次数',
    admin_code_set_times: '设置可用次数',
    admin_code_delete_selected: '删除已选邀请码',
    admin_code_add: '添加邀请码',
    admin_code_fetch_failed: '邀请码列表加载失败：%1。',
    admin_code_delete_ok: '已删除邀请码。',
    admin_code_delete_failed: '邀请码删除失败：%1。',
    admin_times_set_ok: '已更新可用次数。',
    admin_times_set_failed: '可用次数更新失败：%1。',

    paginator_first_page: '第一页',
    paginator_last_page: '最后一页',
    paginator_previous_page: '上一页',
    paginator_next_page: '下一页',
    paginator_per_page: '每页条目：',
    paginator_position_none: '无项目',
    paginator_position_zero: '当前列表无项目，共有%1个项目',
    paginator_position: '第%1到%2个项目，共%3个项目',

    default_prompt_title: '输入一个值',
    default_prompt_label: '值',
    default_prompt_placeholder: '在此输入值',
    default_prompt_yes: '确定',
    default_prompt_no: '取消',

    set_password_prompt_title: '设置用户密码',
    set_password_prompt_label: '新密码',
    set_password_prompt_placeholder: '在此输入新密码',
    set_password_prompt_yes: '设置',
    set_password_prompt_no: '取消',

    delete_user_confirm_title: '删除用户',
    delete_user_confirm_word: '你确定要删除这个用户吗？',
    delete_user_confirm_yes: '删除',
    delete_user_confirm_no: '取消',

    delete_users_confirm_title: '删除已选用户',
    delete_users_confirm_word: '你确定要删除这些用户吗？',
    delete_users_confirm_yes: '删除',
    delete_users_confirm_no: '取消',

    default_choice_title: '选择一个值',
    default_choice_word: '请从下面两个值中选择一个',
    default_choice_right: '右',
    default_choice_left: '左',

    delete_user_choice_title: '处理用户图片',
    delete_user_choice_word: '如何处理该用户上传的图片？',
    delete_user_choice_right: '归入此帐号',
    delete_user_choice_left: '删除',

    delete_users_choice_title: '处理用户图片',
    delete_users_choice_word: '如何处理所选用户上传的图片？',
    delete_users_choice_right: '归入此帐号',
    delete_users_choice_left: '删除',

    add_user_title: '添加用户',
    add_user_username: '用户名',
    add_user_password: '密码',
    add_user_privileged: '赋予高级功能权限',
    add_user_error_user_exist: '用户已存在',
    add_user_cancel: '取消',
    add_user_submit: '添加',
    add_user_success_msg: '已添加用户%1。',
    add_user_error_msg: '用户添加失败：%1。',

    add_code_title: '添加邀请码',
    add_code_code: '邀请代码',
    add_code_times: '可用次数',
    add_code_error_code_exist: '该邀请码已存在',
    add_code_cancel: '取消',
    add_code_submit: '添加',
    add_code_success_msg: '已添加邀请码%1。',
    add_code_error_msg: '邀请码添加失败：%1。',

    code_times_prompt_title: '设置可用次数',
    code_times_prompt_label: '可用次数',
    code_times_prompt_placeholder: '输入一个数字',
    code_times_prompt_yes: '保存',
    code_times_prompt_no: '取消',

    delete_code_confirm_title: '删除邀请码',
    delete_code_confirm_word: '确实要删除这个邀请码吗？',
    delete_code_confirm_yes: '删除',
    delete_code_confirm_no: '取消',

    not_found_title: 'Not found',
    not_found_word: '此页面没有内容。',
    not_found_back: '返回主页',

    format_pref_title: '图像格式偏好设置',
    format_pref_note_title: '提示：',
    format_pref_note_content: '你可以在这里设置你对不同格式图像的偏好。默认情况下服务器会以你浏览器所支持，且文件大小最小的格式提供图片，' +
      '但这需要CPU进行更多运算以显示图片。一般情况下解码时间的差异可以忽略不计，但更小的文件可以显著提高加载速度，因此我们推荐你使用默认设置。' +
      '如果你正在使用一个低性能设备，或你十分关心设备的续航时间，你可以在此手动设置你对各种格式的偏好，我们在提供图片时会优先考虑你设置的顺序。',
    format_pref_support_status: '你浏览器对各种图片格式的支持：',
    format_pref_support_status_detecting: '正在检测……',
    format_pref_support_status_supported: '支持',
    format_pref_support_status_not_supported: '不支持',
    format_pref_support_status_jpeg_png: '所有浏览器都支持PNG和JPEG格式。',
    format_pref_drag_hint: '拖拽以改变顺序：',
    format_pref_cancel: '取消',
    format_pref_reset: '重置',
    format_pref_save: '保存',
    format_pref_save_done: '偏好已保存。',
    format_pref_reset_done: '偏好已重置。',

    about_title: '关于',
    about_content: 'Chromatic是一个专注于优化Web访问体验的图片存储平台。',
    about_privacy: '隐私',
    about_privacy_content: '我们注重对你的隐私保护，仅收集最低限度的必要数据。在你浏览图片时，我们会匿名统计图片的访问次数，' +
      '并依此决定我们是否应该使用更多服务器资源进一步优化浏览体验。如果你设置了图片格式偏好' +
      '，则每当你请求图片（包括在其他网站加载来自本平台的图片）时，都会向服务器发送一个Cookie以告知你的偏好。此Cookie不会被用作其他用途。',
    about_based_on: '鸣谢',
    about_based_content: 'Chromatic的诞生离不开许许多多开源项目的支持。',
    about_license_other: '其他许可',

    info_main: '主页',
    info_about: '关于',

    title_about: '关于',
    title_admin: '管理',
    title_gallery: '图片库',
    title_gallery_me: '我的图片库',
    title_login: '登录',
    title_register: '注册',
    title_not_found: '未知页面',
    title_upload: '上传图片',
    title_uploading: '正在上传，%1个文件已上传',
    title_uploading_error: '正在上传，%1个文件已上传，%2个文件上传失败',
    title_uploaded: '%1个文件上传成功',
    title_uploaded_error: '%1个文件上传成功，%2个文件上传失败',

    time_year: 'y年',
    time_year_post: '%1',
    time_month: 'y年MMM',
    time_month_post: '%1',
    time_week: 'y年第w周',
    time_week_post: '%1',
    time_day: 'mediumDate',
    time_day_post: '%1',

    '0000': '成功',
    '0001': '密码强度过弱',
    '0002': '用户已经存在',
    '0003': '邀请码无效',
    '0004': '用户名或密码不正确',
    '0005': '所选用户不存在',
    '0006': '指定的邀请码已经存在',
    '0007': '指定的邀请码不存在',
    '0008': '请求不合法',
    '0009': '指定的图片不存在',
    '0010': '图片文件已损坏，或不支持此格式',
    '0011': '图片编码失败',
    '0012': '原始图片不存在',
    '0013': '请求缺少认证代码',
    '0014': '认证代码已过期',
    '0015': '权限不足',

    9999: '未知错误',
    http_error: 'HTTP %1',
    net_error: '网络错误',
    action_retry: '重试',
    login_expired: '你的登录信息已过期。请重新登录。',
    other: '(!缺失!)'
  },
  'zh-TW': {
    main_subtitle: '分享你的圖片。為Web訪問最佳化。',
    main_register: '註冊',
    main_login: '登入',
    language_switch: '切換語言',

    header_admin: '管理界面',
    header_upload: '上傳',
    header_upload_frozen: '你的帳號已被停用。',
    header_change_avatar: '更換頭像',
    header_change_password: '更改密碼',
    header_logout: '退出登入',
    header_image_pref: '圖像格式偏好',
    header_gallery: '圖片庫',

    login_title: '登入',
    login_username: '使用者名稱',
    login_password: '密碼',
    login_action_login: '登入',
    login_action_register: '註冊新帳號',
    login_success_message: '登入成功。',
    login_failed_message: '登入失敗：%1。',

    register_title: '註冊',
    register_username: '使用者名稱',
    register_password: '密碼',
    register_password_repeat: '重複密碼',
    register_password_see: '顯示密碼',
    register_password_hide: '隱藏密碼',
    register_code: '邀請碼',
    register_hint_password: '密碼至少8位長，須同時包含數字及大小寫字母',
    register_error_user_exist: '用戶已經存在',
    register_error_password_weak: '密碼強度太弱',
    register_error_password_mismatch: '兩次輸入的密碼不一致',
    register_action_login: '登入已有帳號',
    register_action_register: '註冊',

    guard_need_login_message: '你必須登入才可瀏覽此界面。',

    gallery_broken_image: '圖片不可用',
    gallery_loading: '正在載入……',
    gallery_tag_search: '僅顯示特定標籤的圖片',
    gallery_tag_placeholder: '輸入標籤',
    gallery_tag_failed_message: '標籤載入失敗：%1。',
    gallery_tag_empty: '（空標籤）',
    gallery_group_label: '分組依據：',
    gallery_group_time: '時間',
    gallery_group_tag: '標籤',
    gallery_group_time_label: '分組時長：',
    gallery_group_time_day: '天',
    gallery_group_time_week: '周',
    gallery_group_time_month: '月',
    gallery_group_time_year: '年',
    gallery_select_all_typed: '全選本組',
    gallery_deselect_all_typed: '取消選擇本組',
    gallery_reverse_all_typed: '反選本組',
    gallery_action_edit: '編輯所選圖片',
    gallery_action_code: '獲取所選圖片的發布代碼',
    gallery_action_delete: '刪除所選圖片',
    gallery_action_select_all: '選擇當前所有圖片',
    gallery_action_select_reverse: '反選所有圖片',
    gallery_action_done: '完成',
    gallery_overlay_action_info: '圖片訊息',
    gallery_overlay_action_open: '在新標籤頁內打開圖片',
    gallery_overlay_action_edit: '編輯此圖片訊息',
    gallery_overlay_action_code: '獲取此圖片的發布代碼',
    gallery_overlay_action_delete: '刪除此圖片',
    gallery_overlay_action_close: '回到列表',
    gallery_fetch_failed: '圖片列表載入失敗：%1。',
    gallery_empty: '你還沒有上傳圖片。',
    gallery_empty_other: '無圖片。',
    gallery_empty_upload: '上傳',

    upload_minimize: '最小化',
    upload_expand: '還原',
    upload_close: '關閉',
    upload_title_file_plural_0: '尚無文件',
    upload_title_file_plural_1: '1個文件',
    upload_title_file_plural_other: '個文件',
    upload_title_idle: '上傳',
    upload_title_select_files_p1: '已選擇',
    upload_title_select_files_p2: '',
    upload_title_uploading_fine_p1: '正在上傳，',
    upload_title_uploading_fine_p2: '，',
    upload_title_uploading_fine_p3: '已上傳完畢。',
    upload_title_uploading_some_error_p1: '正在上傳，',
    upload_title_uploading_some_error_p2: '，',
    upload_title_uploading_some_error_p3: '已上傳完畢，',
    upload_title_uploading_some_error_p4: '上傳失敗。',
    upload_title_uploaded_fine: '上傳完畢，全部文件上傳成功。',
    upload_title_uploaded_some_error_p1: '上傳完畢，',
    upload_title_uploaded_some_error_p2: '上傳成功，',
    upload_title_uploaded_some_error_p3: '上傳失敗。',
    upload_drop_file_pre: '將文件拖拽到此處，或',
    upload_drop_file_picker: '選擇文件',
    upload_drop_file_post: '以上傳。',
    upload_drop_file_release: '鬆開滑鼠即可上傳',
    upload_file_name_unknown: '（未知檔案名）',
    upload_file_type_unknown: '（未知格式）',
    upload_submit_no_valid: '你選擇的文件裡沒有圖片。',
    upload_preview_type_header: '顯示模式：',
    upload_preview_type_grid: '網格',
    upload_preview_type_list: '列表',
    upload_preview_limit_height: '限制預覽高度',
    upload_preview_title: '圖片預覽',
    upload_info_form_title: '設置',
    upload_info_tag_header: '圖片標籤',
    upload_info_tag_header_help: '標籤是用來歸類圖像的主要方式',
    upload_info_tag_header_placeholder: '在此輸入標籤，或留空以使用空標籤',
    upload_info_tag_header_hint: '（默認：創建新標籤）',
    upload_info_allow_origins: '可訪問網站',
    upload_info_allow_origins_help: '瀏覽者僅能從這些網站訪問你的圖片',
    upload_info_allow_origins_placeholder: '在此輸入域名，使用逗號或回車分隔',
    upload_info_allow_origins_any: '（任何網站）',
    upload_info_allow_origins_none: '（直接打開）',
    upload_info_allow_origins_exact: '（精確匹配）',
    upload_info_allow_origins_wildcard: '（允許子站）',
    upload_info_allow_origins_bad: '（當前輸入不是一個有效域名）',
    upload_info_allow_origins_exist: '（允許列表已包含此域名）',
    upload_failed_info: '上傳失敗：%1',
    upload_operation_reset: '重設',
    upload_operation_submit: '上傳',

    upload_advanced_button: '高級上傳',
    upload_advanced_title: '高級上傳',
    upload_advanced_warning_head: '警告：',
    upload_advanced_warning_text: '高級上傳允許你手動上傳不同格式的同一張圖片，並直接將上傳的文件提供給用戶。' +
      '服務端不會對上傳的文件進行任何校驗，因此本功能僅面向高級用戶。在操作時請小心。',
    upload_advanced_file_title: '上傳文件',
    upload_advanced_select_file: '選擇文件',
    upload_advanced_selected: '重新選擇',
    upload_advanced_status_not_selected: '尚未選擇文件',
    upload_advanced_status_before: '檔案大小：',
    upload_advanced_status_after: '。',
    upload_advanced_info_title: '設置',
    upload_advanced_operation_cancel: '取消',
    upload_advanced_operation_upload: '上傳',
    upload_advanced_operation_uploading: '正在上傳',
    upload_advanced_operation_uploaded: '關閉',
    upload_advanced_operation_exit: '退出',
    upload_advanced_failed_message: '上傳失敗： %1。',
    upload_advanced_success_message: '上傳成功',
    upload_advanced_progress: '上傳進度',

    edit_images_title: '編輯圖片',
    edit_images_tab_tag: '標籤',
    edit_images_title_tag: '更改圖片標籤',
    edit_images_tab_origins: '可訪問網站',
    edit_images_title_origins: '更改圖片可訪問網站',

    edit_images_result_success: '圖片編輯成功。',
    edit_images_result_failed: '圖片編輯失敗：%1。',

    dialog_cancel: '取消',
    dialog_submit: '確定',

    default_confirm_title: '確認',
    default_confirm_word: '確定要執行動作嗎？',
    default_confirm_yes: '確定',
    default_confirm_no: '取消',

    delete_select_confirm_title: '刪除圖片',
    delete_select_confirm_word: '確定要刪除選擇的圖片嗎？',
    delete_select_confirm_yes: '刪除',
    delete_select_confirm_no: '取消',

    delete_this_confirm_title: '刪除此圖片',
    delete_this_confirm_word: '確定要刪除這張圖片嗎？',
    delete_this_confirm_yes: '刪除',
    delete_this_confirm_no: '取消',

    upload_confirm_title: '中止上傳並退出',
    upload_confirm_word: '確定要退出嗎？部分文件可能不會被上傳。',
    upload_confirm_yes: '退出',
    upload_confirm_no: '取消',

    delete_images_result_success: '圖片已刪除。',
    delete_images_result_failed: '圖片刪除失敗：%1。',

    generate_code_title: '生成發布代碼',
    generate_code_type: '代碼類型',
    generate_code_type_label: '選擇一個代碼類型',
    generate_type_html: 'HTML',
    generate_type_bbcode: 'BBCode',
    generate_type_url: '連結',
    generate_type_custom: '自訂',
    generate_custom_template: '模板',
    generate_custom_template_placeholder: '每張圖片的代碼模板',
    generate_custom_template_hint: '請使用%url%標註放置圖片連結的位置',
    generate_custom_separator: '分隔內容',
    generate_custom_separator_placeholder: '置於圖片間的代碼',
    generate_custom_separator_hint: '分隔代碼將置於每兩張圖片代碼的中間',
    generate_result_copy: '複製',
    generate_result_copied: '代碼已複製',
    generate_code_done: '完成',
    generate_sort_title: '排序圖片',
    generate_sort_reverse: '反序',

    info_title: '圖片訊息',
    info_user: '所有者',
    info_tag: '標籤',
    info_upload_time: '上傳時間',
    info_view: '瀏覽量',
    info_origins: '允許訪問的站點',
    info_formats: '可用格式',
    info_formats_available: '此格式可用',
    info_formats_encoding: '此格式正在轉檔，即將可用',
    info_done: '關閉',

    change_password_title: '更改密碼',
    change_password_old: '舊密碼',
    change_password_new: '新密碼',
    change_password_cancel: '取消',
    change_password_submit: '更改',
    change_password_failed: '更改密碼失敗：%1。',
    change_password_succeed: '密碼已更改。請重新登入。',

    change_avatar_title: '更換頭像',
    change_avatar_title_pick_file: '第一步：請選擇一張圖片',
    change_avatar_file_selector: '選擇圖片',
    change_avatar_file_bad: '圖片載入失敗。請確認這是一個圖片文件。',
    change_avatar_title_crop: '第二步：裁剪圖片',
    change_avatar_preview_no_file: '請先選擇一張圖片，進行裁剪。',
    change_avatar_preview: '頭像預覽',
    change_avatar_success: '頭像已更換。',
    change_avatar_failed: '頭像更換失敗：%1',
    change_avatar_cancel: '取消',
    change_avatar_submit: '保存',

    admin_user: '用戶',
    admin_code: '邀請碼',
    admin_user_search: '僅顯示使用者名稱包含關鍵字的用戶',
    admin_user_search_placeholder: '輸入關鍵字',
    admin_user_fetch_failed: '用戶列表獲取失敗：%1。',
    admin_user_username: '使用者名稱',
    admin_user_privileged: '進階功能權限',
    admin_user_privileged_set: '已修改用戶權限。',
    admin_user_privileged_failed: '用戶權限修改失敗：%1。',
    admin_user_frozen: '凍結',
    admin_user_frozen_set: '已修改用戶凍結狀態。',
    admin_user_frozen_failed: '用戶凍結狀態修改失敗：%1。',
    admin_operation: '操作',
    admin_user_set_password: '設置密碼',
    admin_user_password_ok: '密碼已修改。',
    admin_user_password_failed: '密碼修改失敗：%1。',
    admin_user_set_avatar: '設置頭像',
    admin_user_check_gallery: '查看用戶圖片庫',
    admin_delete: '刪除',
    admin_user_delete_ok: '用戶已刪除。',
    admin_user_delete_failed: '用戶刪除失敗：%1。',
    admin_user_delete_selected: '刪除已選用戶',
    admin_user_delete_selected_ok: '所選用戶已刪除。',
    admin_user_delete_selected_failed: '所選用戶刪除失敗：%1。',
    admin_user_add: '添加用戶',
    admin_code_code: '邀請碼',
    admin_code_times: '可用次數',
    admin_code_set_times: '設置可用次數',
    admin_code_delete_selected: '刪除已選邀請碼',
    admin_code_add: '添加邀請碼',
    admin_code_fetch_failed: '邀請碼列表載入失敗：%1。',
    admin_code_delete_ok: '已刪除邀請碼。',
    admin_code_delete_failed: '邀請碼刪除失敗：%1。',
    admin_times_set_ok: '已更新可用次數。',
    admin_times_set_failed: '可用次數更新失敗：%1。',

    paginator_first_page: '第一頁',
    paginator_last_page: '最後一頁',
    paginator_previous_page: '上一頁',
    paginator_next_page: '下一頁',
    paginator_per_page: '每頁條目：',
    paginator_position_none: '無項目',
    paginator_position_zero: '當前列表無項目，共有%1個項目',
    paginator_position: '第%1到%2個項目，共%3個項目',

    default_prompt_title: '輸入一個值',
    default_prompt_label: '值',
    default_prompt_placeholder: '在此輸入值',
    default_prompt_yes: '確定',
    default_prompt_no: '取消',

    set_password_prompt_title: '設置用戶密碼',
    set_password_prompt_label: '新密碼',
    set_password_prompt_placeholder: '在此輸入新密碼',
    set_password_prompt_yes: '設置',
    set_password_prompt_no: '取消',

    delete_user_confirm_title: '刪除用戶',
    delete_user_confirm_word: '你確定要刪除這個用戶嗎？',
    delete_user_confirm_yes: '刪除',
    delete_user_confirm_no: '取消',

    delete_users_confirm_title: '刪除已選用戶',
    delete_users_confirm_word: '你確定要刪除這些用戶嗎？',
    delete_users_confirm_yes: '刪除',
    delete_users_confirm_no: '取消',

    default_choice_title: '選擇一個值',
    default_choice_word: '請從下面兩個值中選擇一個',
    default_choice_right: '右',
    default_choice_left: '左',

    delete_user_choice_title: '處理用戶圖片',
    delete_user_choice_word: '如何處理該用戶上傳的圖片？',
    delete_user_choice_right: '歸入此帳號',
    delete_user_choice_left: '刪除',

    delete_users_choice_title: '處理用戶圖片',
    delete_users_choice_word: '如何處理所選用戶上傳的圖片？',
    delete_users_choice_right: '歸入此帳號',
    delete_users_choice_left: '刪除',

    add_user_title: '添加用戶',
    add_user_username: '使用者名稱',
    add_user_password: '密碼',
    add_user_privileged: '賦予進階功能權限',
    add_user_error_user_exist: '用戶已存在',
    add_user_cancel: '取消',
    add_user_submit: '添加',
    add_user_success_msg: '已添加用戶%1。',
    add_user_error_msg: '用戶添加失敗：%1。',

    add_code_title: '添加邀請碼',
    add_code_code: '邀請代碼',
    add_code_times: '可用次數',
    add_code_error_code_exist: '該邀請碼已存在',
    add_code_cancel: '取消',
    add_code_submit: '添加',
    add_code_success_msg: '已添加邀請碼%1。',
    add_code_error_msg: '邀請碼添加失敗：%1。',

    code_times_prompt_title: '設置可用次數',
    code_times_prompt_label: '可用次數',
    code_times_prompt_placeholder: '輸入一個數字',
    code_times_prompt_yes: '保存',
    code_times_prompt_no: '取消',

    delete_code_confirm_title: '刪除邀請碼',
    delete_code_confirm_word: '確定要刪除這個邀請碼嗎？',
    delete_code_confirm_yes: '刪除',
    delete_code_confirm_no: '取消',

    not_found_title: 'Not found',
    not_found_word: '此頁面沒有內容。',
    not_found_back: '返回首頁',

    format_pref_title: '圖像格式偏好設置',
    format_pref_note_title: '提示：',
    format_pref_note_content: '你可以在這裡設置你對不同格式圖像的偏好。默認情況下伺服器會以你瀏覽器所支持，且檔案大小最小的格式提供圖片，' +
      '但這需要CPU進行更多運算以顯示圖片。一般情況下解碼時間的差異可以忽略不計，但更小的文件可以顯著提高載入速度，因此我們推薦你使用默認設置。' +
      '如果你正在使用一個低性能設備，或你十分關心設備的續航時間，你可以在此手動設置你對各種格式的偏好，我們在提供圖片時會優先考慮你設置的順序。',
    format_pref_support_status: '你瀏覽器對各種圖片格式的支持：',
    format_pref_support_status_detecting: '正在檢測……',
    format_pref_support_status_supported: '支持',
    format_pref_support_status_not_supported: '不支持',
    format_pref_support_status_jpeg_png: '所有瀏覽器都支持PNG和JPEG格式。',
    format_pref_drag_hint: '拖拽以改變順序：',
    format_pref_cancel: '取消',
    format_pref_reset: '重設',
    format_pref_save: '保存',
    format_pref_save_done: '偏好已保存。',
    format_pref_reset_done: '偏好已重設。',

    about_title: '關於',
    about_content: 'Chromatic是一個專注於最佳化Web訪問體驗的圖片儲存平台。',
    about_privacy: '隱私',
    about_privacy_content: '我們注重對你的隱私保護，僅收集最低限度的必要數據。在你瀏覽圖片時，我們會匿名統計圖片的訪問次數，' +
      '並依此決定我們是否應該使用更多伺服器資源進一步最佳化瀏覽體驗。如果你設置了圖片格式偏好' +
      '，則每當你請求圖片（包括在其他網站載入來自本平台的圖片）時，都會向伺服器發送一個Cookie以告知你的偏好。此Cookie不會被用作其他用途。',
    about_based_on: '鳴謝',
    about_based_content: 'Chromatic的誕生離不開許許多多開源項目的支持。',
    about_license_other: '其他許可',

    info_main: '首頁',
    info_about: '關於',

    title_about: '關於',
    title_admin: '管理',
    title_gallery: '圖片庫',
    title_gallery_me: '我的圖片庫',
    title_login: '登入',
    title_register: '註冊',
    title_not_found: '未知頁面',
    title_upload: '上傳圖片',
    title_uploading: '正在上傳，%1個文件已上傳',
    title_uploading_error: '正在上傳，%1個文件已上傳，%2個文件上傳失敗',
    title_uploaded: '%1個文件上傳成功',
    title_uploaded_error: '%1個文件上傳成功，%2個文件上傳失敗',

    time_year: 'y年',
    time_year_post: '%1',
    time_month: 'y年MMM',
    time_month_post: '%1',
    time_week: 'y年第w周',
    time_week_post: '%1',
    time_day: 'mediumDate',
    time_day_post: '%1',

    '0000': '成功',
    '0001': '密碼強度太弱',
    '0002': '用戶已經存在',
    '0003': '邀請碼無效',
    '0004': '使用者名稱或密碼不正確',
    '0005': '所選用戶不存在',
    '0006': '指定的邀請碼已經存在',
    '0007': '指定的邀請碼不存在',
    '0008': '請求不合法',
    '0009': '指定的圖片不存在',
    '0010': '圖片文件已損壞，或不支持此格式',
    '0011': '圖片編碼失敗',
    '0012': '原始圖片不存在',
    '0013': '請求缺少認證代碼',
    '0014': '認證代碼已過期',
    '0015': '權限不足',

    9999: '未知錯誤',
    http_error: 'HTTP %1',
    net_error: '網路錯誤',
    action_retry: '重試',
    login_expired: '你的登入訊息已過期。請重新登入。',
    other: '(!缺失!)'
  }
};

console.log(JSON.stringify(TransTable));
*/
// tslint:disable-next-line:max-line-length
const langJSON = `{"en":{"9999":"Unknown error","main_subtitle":"Share your images. Optimized for web.","main_register":"Register","main_login":"Login","language_switch":"Switch Language","header_admin":"Admin area","header_upload":"Upload","header_upload_frozen":"Your account is suspended.","header_change_avatar":"Change avatar","header_change_password":"Change Password","header_logout":"Logout","header_image_pref":"Image preference","header_gallery":"Gallery","login_title":"Login","login_username":"Username","login_password":"Password","login_action_login":"Login","login_action_register":"Register account","login_success_message":"Login successful.","login_failed_message":"Login failed: %1.","register_title":"Register","register_username":"Username","register_password":"Password","register_password_repeat":"Repeat password","register_password_see":"Unmask password","register_password_hide":"Mask password","register_code":"Invite code","register_hint_password":"At least 8 characters, contains upper, lower letter and number","register_error_user_exist":"User already exist","register_error_password_weak":"Password too weak","register_error_password_mismatch":"Passwords didn't match","register_action_login":"I have account","register_action_register":"Register","guard_need_login_message":"You must login to access this page.","gallery_broken_image":"Image not available","gallery_loading":"Loading...","gallery_tag_search":"Show specified tag only...","gallery_tag_placeholder":"Input tag here","gallery_tag_failed_message":"Failed loading tags: %1.","gallery_tag_empty":"(Empty tag)","gallery_group_label":"Group images by: ","gallery_group_time":"Time","gallery_group_tag":"Tag","gallery_group_time_label":"Time span: ","gallery_group_time_day":"Day","gallery_group_time_week":"Week","gallery_group_time_month":"Month","gallery_group_time_year":"Year","gallery_select_all_typed":"Select all of this group","gallery_deselect_all_typed":"Deselect all of this group","gallery_reverse_all_typed":"Reverse select images of this group","gallery_action_edit":"Edit selected images","gallery_action_code":"Get code of selected images to publish","gallery_action_delete":"Delete selected images","gallery_action_select_all":"Select all images","gallery_action_select_reverse":"Reverse selection","gallery_action_done":"Done","gallery_overlay_action_info":"Image info","gallery_overlay_action_open":"Open image file in new page","gallery_overlay_action_edit":"Edit this image","gallery_overlay_action_code":"Get code of this image to publish","gallery_overlay_action_delete":"Delete this image","gallery_overlay_action_close":"Return to gallery","gallery_fetch_failed":"Failed loading images: %1.","gallery_empty":"Your gallery is empty.","gallery_empty_other":"Nothing here.","gallery_empty_upload":"Upload image","upload_minimize":"Minimize","upload_expand":"Expand","upload_close":"Close","upload_title_file_plural_0":"no file","upload_title_file_plural_1":"1 file","upload_title_file_plural_other":"files","upload_title_idle":"Upload","upload_title_select_files_p1":"","upload_title_select_files_p2":"selected for upload","upload_title_uploading_fine_p1":"Uploading files,","upload_title_uploading_fine_p2":", ","upload_title_uploading_fine_p3":"finished","upload_title_uploading_some_error_p1":"Uploading files,","upload_title_uploading_some_error_p2":",","upload_title_uploading_some_error_p3":"finished,","upload_title_uploading_some_error_p4":"failed","upload_title_uploaded_fine":"Upload finished, all files succeed","upload_title_uploaded_some_error_p1":"Upload finished,","upload_title_uploaded_some_error_p2":"succeed,","upload_title_uploaded_some_error_p3":"failed","upload_drop_file_pre":"Drop image files here, or ","upload_drop_file_picker":"Select files","upload_drop_file_post":".","upload_drop_file_release":"Release your mouse to submit files.","upload_file_name_unknown":"(Unknown filename)","upload_file_type_unknown":"(Unknown type)","upload_submit_no_valid":"No valid image file found in your selected files.","upload_preview_type_header":"Display mode: ","upload_preview_type_grid":"Grid","upload_preview_type_list":"List","upload_preview_limit_height":"Limit height","upload_preview_title":"Image Preview","upload_info_form_title":"Settings","upload_info_tag_header":"Tag for images","upload_info_tag_header_help":"Tag is the primary way to group your images","upload_info_tag_header_placeholder":"Type tag here, or keep blank to use empty tag","upload_info_tag_header_hint":"(Default: tag will set to your input)","upload_info_allow_origins":"Allow origins","upload_info_allow_origins_help":"User can only access images from these sites","upload_info_allow_origins_placeholder":"Type domain here, split with comma or enter","upload_info_allow_origins_any":" (Any site)","upload_info_allow_origins_none":" (Direct access)","upload_info_allow_origins_exact":" (Exact match)","upload_info_allow_origins_wildcard":" (Wildcard match)","upload_info_allow_origins_bad":" (Current input is not a valid domain)","upload_info_allow_origins_exist":" (Already covered)","upload_failed_info":"Upload failed: %1","upload_operation_reset":"Reset","upload_operation_submit":"Upload","upload_advanced_button":"Advanced upload","upload_advanced_title":"Advanced upload","upload_advanced_warning_head":"Warning: ","upload_advanced_warning_text":"Advanced upload allows you to upload files in different formats of the same image, and serve to the user as is. Server will not do any check, even not checking if it is a valid image file, so as it called \\"Advanced\\". Please be cautious.","upload_advanced_file_title":"Pick files","upload_advanced_select_file":"Select file","upload_advanced_selected":"Reselect","upload_advanced_status_not_selected":"Not selected","upload_advanced_status_before":"File size:","upload_advanced_status_after":".","upload_advanced_info_title":"Settings","upload_advanced_operation_cancel":"Cancel","upload_advanced_operation_upload":"Upload","upload_advanced_operation_uploading":"Uploading","upload_advanced_operation_uploaded":"Close","upload_advanced_operation_exit":"Exit","upload_advanced_failed_message":"Uploading file failed: %1.","upload_advanced_success_message":"Upload successful.","upload_advanced_progress":"Upload Progress","edit_images_title":"Edit images","edit_images_tab_tag":"Tag","edit_images_title_tag":"Change tag of images","edit_images_tab_origins":"Origins","edit_images_title_origins":"Change origins of images","edit_images_result_success":"Image edit successful.","edit_images_result_failed":"Image edit failed: %1.","dialog_cancel":"Cancel","dialog_submit":"OK","default_confirm_title":"Confirmation","default_confirm_word":"Are you sure to process?","default_confirm_yes":"Confirm","default_confirm_no":"Cancel","delete_select_confirm_title":"Delete images","delete_select_confirm_word":"Are you sure to delete selected images?","delete_select_confirm_yes":"Delete","delete_select_confirm_no":"Cancel","delete_this_confirm_title":"Delete this image","delete_this_confirm_word":"Are you sure to delete this image?","delete_this_confirm_yes":"Delete","delete_this_confirm_no":"Cancel","upload_confirm_title":"Abort upload and exit","upload_confirm_word":"Are you sure to exit? Some files may not be uploaded if you exit now.","upload_confirm_yes":"Exit","upload_confirm_no":"Cancel","delete_images_result_success":"Image deleted.","delete_images_result_failed":"Image delete failed: %1.","generate_code_title":"Generate Code for Publish","generate_code_type":"Code type:","generate_code_type_label":"Select a code type","generate_type_html":"HTML","generate_type_bbcode":"BBCode","generate_type_url":"URL","generate_type_custom":"Customize","generate_custom_template":"Template","generate_custom_template_placeholder":"Template code for each image","generate_custom_template_hint":"Use %url% to mark the position to place url","generate_custom_separator":"Separator","generate_custom_separator_placeholder":"Separator code between images","generate_custom_separator_hint":"Separator code will be placed between codes of each image","generate_result_copy":"Copy","generate_result_copied":"Code copied.","generate_code_done":"Done","generate_sort_title":"Sort images","generate_sort_reverse":"Reverse","info_title":"Image info","info_user":"Uploader","info_tag":"Image tag","info_upload_time":"Upload time","info_view":"View count","info_origins":"Allowed origin sites","info_formats":"Available formats","info_formats_available":"This format is available","info_formats_encoding":"This format is being transcode, and will be available soon","info_done":"Close","change_password_title":"Change Password","change_password_old":"Old password","change_password_new":"New password","change_password_cancel":"Cancel","change_password_submit":"Change","change_password_failed":"Change password failed: %1.","change_password_succeed":"Password changed. Please re-login.","change_avatar_title":"Change Avatar","change_avatar_title_pick_file":"1. Pick an image","change_avatar_file_selector":"Select image","change_avatar_file_bad":"Failed loading image. Is this a valid image file?","change_avatar_title_crop":"2. Crop your image","change_avatar_preview_no_file":"Please select an image first.","change_avatar_preview":"Avatar preview","change_avatar_success":"Avatar changed.","change_avatar_failed":"Failed change avatar: %1","change_avatar_cancel":"Cancel","change_avatar_submit":"Save","admin_user":"User","admin_code":"Code","admin_user_search":"Show users name contains keyword only...","admin_user_search_placeholder":"Input keyword here","admin_user_fetch_failed":"Failed fetching user list: %1.","admin_user_username":"User","admin_user_privileged":"Privileged","admin_user_privileged_set":"User privilege status changed.","admin_user_privileged_failed":"Failed changing user privilege status: %1.","admin_user_frozen":"Frozen","admin_user_frozen_set":"User freeze status changed.","admin_user_frozen_failed":"Failed changing user freeze status: %1.","admin_operation":"Operations","admin_user_set_password":"Set Password","admin_user_password_ok":"User password changed.","admin_user_password_failed":"Failed changing user password: %1.","admin_user_set_avatar":"Set Avatar","admin_user_check_gallery":"Check Gallery","admin_delete":"Delete","admin_user_delete_ok":"User deleted.","admin_user_delete_failed":"Failed deleting user: %1.","admin_user_delete_selected":"Delete selected users","admin_user_delete_selected_ok":"Selected users deleted.","admin_user_delete_selected_failed":"Failed deleting selected users: %1.","admin_user_add":"Add user","admin_code_code":"Invite code","admin_code_times":"Available times","admin_code_set_times":"Set available times","admin_code_delete_selected":"Delete selected codes","admin_code_add":"Add invite code","admin_code_fetch_failed":"Failed fetching invite code list: %1.","admin_code_delete_ok":"Invite code deleted.","admin_code_delete_failed":"Failed deleting invite code: %1.","admin_times_set_ok":"Available times updated.","admin_times_set_failed":"Failed updating available times: %1.","paginator_first_page":"First page","paginator_last_page":"Last page","paginator_previous_page":"Previous page","paginator_next_page":"Next page","paginator_per_page":"Items per page: ","paginator_position_none":"No item","paginator_position_zero":"0, total %1","paginator_position":"%1 – %2 of %3","default_prompt_title":"Input a value","default_prompt_label":"The value","default_prompt_placeholder":"Input value here","default_prompt_yes":"Submit","default_prompt_no":"Cancel","set_password_prompt_title":"Set user password","set_password_prompt_label":"New Password","set_password_prompt_placeholder":"Input new password here","set_password_prompt_yes":"Set","set_password_prompt_no":"Cancel","delete_user_confirm_title":"Delete user","delete_user_confirm_word":"Are you sure to delete this user?","delete_user_confirm_yes":"Delete","delete_user_confirm_no":"Cancel","delete_users_confirm_title":"Delete selected users","delete_users_confirm_word":"Are you sure to delete selected users?","delete_users_confirm_yes":"Delete","delete_users_confirm_no":"Cancel","default_choice_title":"Select one value","default_choice_word":"Please select one of the two values","default_choice_right":"Right","default_choice_left":"Left","delete_user_choice_title":"Image handling","delete_user_choice_word":"How to handle images (if any) of this user?","delete_user_choice_right":"Adopt","delete_user_choice_left":"Delete","delete_users_choice_title":"Image handling","delete_users_choice_word":"How to handle images (if any) of the selected users?","delete_users_choice_right":"Adopt","delete_users_choice_left":"Delete","add_user_title":"Add user","add_user_username":"Username","add_user_password":"Password","add_user_privileged":"Privilege this user","add_user_error_user_exist":"User already exist","add_user_cancel":"Cancel","add_user_submit":"Add","add_user_success_msg":"User %1 added.","add_user_error_msg":"Failed adding user: %1.","add_code_title":"Add invite code","add_code_code":"Code token","add_code_times":"Available times","add_code_error_code_exist":"Code already exist","add_code_cancel":"Cancel","add_code_submit":"Add","add_code_success_msg":"Code %1 added.","add_code_error_msg":"Failed adding code: %1.","code_times_prompt_title":"Set available times","code_times_prompt_label":"Available times","code_times_prompt_placeholder":"Input a number here","code_times_prompt_yes":"Save","code_times_prompt_no":"Cancel","delete_code_confirm_title":"Delete code","delete_code_confirm_word":"Are you sure to delete this code?","delete_code_confirm_yes":"Delete","delete_code_confirm_no":"Cancel","not_found_title":"Not found","not_found_word":"Nothing available here.","not_found_back":"To main page","format_pref_title":"Format preference settings","format_pref_note_title":"Note: ","format_pref_note_content":"Here you can set your image format preference. By default we serve you image in the format that has minimal size while supported by your browser, and this means CPU will do more work to decode the image. Usually the difference is small, but smaller file loads significantly faster, so we recommend you to keep the default. However, if you are using a low-end device or you really cares battery life, you can manually set your preference below, and we will respect your settings and try to serve you images with formats in your desired order.","format_pref_support_status":"Your browser's support to different formats: ","format_pref_support_status_detecting":"Detecting...","format_pref_support_status_supported":"Supported","format_pref_support_status_not_supported":"Not supported","format_pref_support_status_jpeg_png":"Every browser supports PNG and JPEG.","format_pref_drag_hint":"Drag to sort the formats:","format_pref_cancel":"Cancel","format_pref_reset":"Reset","format_pref_save":"Save","format_pref_save_done":"Preference saved.","format_pref_reset_done":"Preference cleared.","about_title":"About","about_content":"Chromatic is an image store platform specially targeted on optimizing web access experience.","about_privacy":"Privacy","about_privacy_content":"We value your privacy, and collects only necessary data. We do anonymous count when you are requesting images from us, and the data is solely used to decide if we should put more resource to optimize load experience. If you set the format preference, then a cookie will be sent everytime you request images from us (include from other sites), to let us know your preference. We won't use the cookie to do any other thing.","about_based_on":"Credits","about_based_content":"Chromatic is made possible by many open source projects.","about_license_other":"Other","info_main":"Main Page","info_about":"About","title_about":"About","title_admin":"Admin","title_gallery":"Gallery","title_gallery_me":"My gallery","title_login":"Login","title_register":"Register","title_not_found":"Not Found","title_upload":"Upload","title_uploading":"Uploading, %1 files finished","title_uploading_error":"Uploading, %1 files finished, %2 files failed","title_uploaded":"%1 files uploaded","title_uploaded_error":"%1 files uploaded, %2 files failed","time_year":"y","time_year_post":"Year %1","time_month":"MMM, y","time_month_post":"%1","time_week":"w, y","time_week_post":"Week %1","time_day":"mediumDate","time_day_post":"%1","0000":"Successful","0001":"Password strength too weak","0002":"User already exist","0003":"The invite code is invalid","0004":"Wrong account or password","0005":"The specified user doesn't exist","0006":"The specified invite code already exist","0007":"The specified invite code doesn't exist","0008":"Bad request","0009":"The specified image doesn't exist","0010":"The image is broken or unsupported","0011":"Failed encoding image","0012":"Original image doesn't exist","0013":"Request being made without credential","0014":"Credential used in request has expired","0015":"Permission denied","http_error":"HTTP %1","net_error":"Network error","action_retry":"Retry","login_expired":"Your login info has expired and you have to login.","other":"(!Missing!)"},"zh-CN":{"9999":"未知错误","main_subtitle":"分享你的图片。为Web访问优化。","main_register":"注册","main_login":"登录","language_switch":"切换语言","header_admin":"管理界面","header_upload":"上传","header_upload_frozen":"你的账号已被停用。","header_change_avatar":"更换头像","header_change_password":"更改密码","header_logout":"退出登录","header_image_pref":"图像格式偏好","header_gallery":"图片库","login_title":"登录","login_username":"用户名","login_password":"密码","login_action_login":"登录","login_action_register":"注册新帐号","login_success_message":"登录成功。","login_failed_message":"登录失败：%1。","register_title":"注册","register_username":"用户名","register_password":"密码","register_password_repeat":"重复密码","register_password_see":"显示密码","register_password_hide":"隐藏密码","register_code":"邀请码","register_hint_password":"密码至少8位长，须同时包含数字及大小写字母","register_error_user_exist":"用户已经存在","register_error_password_weak":"密码强度太弱","register_error_password_mismatch":"两次输入的密码不一致","register_action_login":"登录已有帐号","register_action_register":"注册","guard_need_login_message":"你必须登录才可浏览此界面。","gallery_broken_image":"图片不可用","gallery_loading":"正在加载……","gallery_tag_search":"仅显示特定标签的图片","gallery_tag_placeholder":"输入标签","gallery_tag_failed_message":"标签加载失败：%1。","gallery_tag_empty":"（空标签）","gallery_group_label":"分组依据：","gallery_group_time":"时间","gallery_group_tag":"标签","gallery_group_time_label":"分组时长：","gallery_group_time_day":"天","gallery_group_time_week":"周","gallery_group_time_month":"月","gallery_group_time_year":"年","gallery_select_all_typed":"全选本组","gallery_deselect_all_typed":"取消选择本组","gallery_reverse_all_typed":"反选本组","gallery_action_edit":"编辑所选图片","gallery_action_code":"获取所选图片的发布代码","gallery_action_delete":"删除所选图片","gallery_action_select_all":"选择当前所有图片","gallery_action_select_reverse":"反选所有图片","gallery_action_done":"完成","gallery_overlay_action_info":"图片信息","gallery_overlay_action_open":"在新标签页内打开图片","gallery_overlay_action_edit":"编辑此图片信息","gallery_overlay_action_code":"获取此图片的发布代码","gallery_overlay_action_delete":"删除此图片","gallery_overlay_action_close":"回到列表","gallery_fetch_failed":"图片列表加载失败：%1。","gallery_empty":"你还没有上传图片。","gallery_empty_other":"无图片。","gallery_empty_upload":"上传","upload_minimize":"最小化","upload_expand":"还原","upload_close":"关闭","upload_title_file_plural_0":"尚无文件","upload_title_file_plural_1":"1个文件","upload_title_file_plural_other":"个文件","upload_title_idle":"上传","upload_title_select_files_p1":"已选择","upload_title_select_files_p2":"","upload_title_uploading_fine_p1":"正在上传，","upload_title_uploading_fine_p2":"，","upload_title_uploading_fine_p3":"已上传完毕。","upload_title_uploading_some_error_p1":"正在上传，","upload_title_uploading_some_error_p2":"，","upload_title_uploading_some_error_p3":"已上传完毕，","upload_title_uploading_some_error_p4":"上传失败。","upload_title_uploaded_fine":"上传完毕，全部文件上传成功。","upload_title_uploaded_some_error_p1":"上传完毕，","upload_title_uploaded_some_error_p2":"上传成功，","upload_title_uploaded_some_error_p3":"上传失败。","upload_drop_file_pre":"将文件拖拽到此处，或","upload_drop_file_picker":"选择文件","upload_drop_file_post":"以上传。","upload_drop_file_release":"松开鼠标即可上传","upload_file_name_unknown":"（未知文件名）","upload_file_type_unknown":"（未知格式）","upload_submit_no_valid":"你选择的文件里没有图片。","upload_preview_type_header":"显示模式：","upload_preview_type_grid":"网格","upload_preview_type_list":"列表","upload_preview_limit_height":"限制预览高度","upload_preview_title":"图片预览","upload_info_form_title":"设置","upload_info_tag_header":"图片标签","upload_info_tag_header_help":"标签是用来归类图像的主要方式","upload_info_tag_header_placeholder":"在此输入标签，或留空以使用空标签","upload_info_tag_header_hint":"（默认：创建新标签）","upload_info_allow_origins":"可访问网站","upload_info_allow_origins_help":"浏览者仅能从这些网站访问你的图片","upload_info_allow_origins_placeholder":"在此输入域名，使用逗号或回车分隔","upload_info_allow_origins_any":"（任何网站）","upload_info_allow_origins_none":"（直接打开）","upload_info_allow_origins_exact":"（精确匹配）","upload_info_allow_origins_wildcard":"（允许子站）","upload_info_allow_origins_bad":"（当前输入不是一个有效域名）","upload_info_allow_origins_exist":"（允许列表已包含此域名）","upload_failed_info":"上传失败：%1","upload_operation_reset":"重置","upload_operation_submit":"上传","upload_advanced_button":"高级上传","upload_advanced_title":"高级上传","upload_advanced_warning_head":"警告：","upload_advanced_warning_text":"高级上传允许你手动上传不同格式的同一张图片，并直接将上传的文件提供给用户。服务端不会对上传的文件进行任何校验，因此本功能仅面向高级用户。在操作时请小心。","upload_advanced_file_title":"上传文件","upload_advanced_select_file":"选择文件","upload_advanced_selected":"重新选择","upload_advanced_status_not_selected":"尚未选择文件","upload_advanced_status_before":"文件大小：","upload_advanced_status_after":"。","upload_advanced_info_title":"设置","upload_advanced_operation_cancel":"取消","upload_advanced_operation_upload":"上传","upload_advanced_operation_uploading":"正在上传","upload_advanced_operation_uploaded":"关闭","upload_advanced_operation_exit":"退出","upload_advanced_failed_message":"上传失败： %1。","upload_advanced_success_message":"上传成功","upload_advanced_progress":"上传进度","edit_images_title":"编辑图片","edit_images_tab_tag":"标签","edit_images_title_tag":"更改图片标签","edit_images_tab_origins":"可访问网站","edit_images_title_origins":"更改图片可访问网站","edit_images_result_success":"图片编辑成功。","edit_images_result_failed":"图片编辑失败：%1。","dialog_cancel":"取消","dialog_submit":"确定","default_confirm_title":"确认","default_confirm_word":"确实要执行动作吗？","default_confirm_yes":"确定","default_confirm_no":"取消","delete_select_confirm_title":"删除图片","delete_select_confirm_word":"确实要删除选择的图片吗？","delete_select_confirm_yes":"删除","delete_select_confirm_no":"取消","delete_this_confirm_title":"删除此图片","delete_this_confirm_word":"确实要删除这张图片吗？","delete_this_confirm_yes":"删除","delete_this_confirm_no":"取消","upload_confirm_title":"中止上传并退出","upload_confirm_word":"确实要退出吗？部分文件可能不会被上传。","upload_confirm_yes":"退出","upload_confirm_no":"取消","delete_images_result_success":"图片已删除。","delete_images_result_failed":"图片删除失败：%1。","generate_code_title":"生成发布代码","generate_code_type":"代码类型","generate_code_type_label":"选择一个代码类型","generate_type_html":"HTML","generate_type_bbcode":"BBCode","generate_type_url":"链接","generate_type_custom":"自定义","generate_custom_template":"模板","generate_custom_template_placeholder":"每张图片的代码模板","generate_custom_template_hint":"请使用%url%标注放置图片链接的位置","generate_custom_separator":"分隔内容","generate_custom_separator_placeholder":"置于图片间的代码","generate_custom_separator_hint":"分隔代码将置于每两张图片代码的中间","generate_result_copy":"复制","generate_result_copied":"代码已复制","generate_code_done":"完成","generate_sort_title":"排序图片","generate_sort_reverse":"反序","info_title":"图片信息","info_user":"所有者","info_tag":"标签","info_upload_time":"上传时间","info_view":"浏览量","info_origins":"允许访问的站点","info_formats":"可用格式","info_formats_available":"此格式可用","info_formats_encoding":"此格式正在转码，即将可用","info_done":"关闭","change_password_title":"更改密码","change_password_old":"旧密码","change_password_new":"新密码","change_password_cancel":"取消","change_password_submit":"更改","change_password_failed":"更改密码失败：%1。","change_password_succeed":"密码已更改。请重新登录。","change_avatar_title":"更换头像","change_avatar_title_pick_file":"第一步：请选择一张图片","change_avatar_file_selector":"选择图片","change_avatar_file_bad":"图片加载失败。请确认这是一个图片文件。","change_avatar_title_crop":"第二步：裁剪图片","change_avatar_preview_no_file":"请先选择一张图片，进行裁剪。","change_avatar_preview":"头像预览","change_avatar_success":"头像已更换。","change_avatar_failed":"头像更换失败：%1","change_avatar_cancel":"取消","change_avatar_submit":"保存","admin_user":"用户","admin_code":"邀请码","admin_user_search":"仅显示用户名包含关键字的用户","admin_user_search_placeholder":"输入关键字","admin_user_fetch_failed":"用户列表获取失败：%1。","admin_user_username":"用户名","admin_user_privileged":"高级功能权限","admin_user_privileged_set":"已修改用户权限。","admin_user_privileged_failed":"用户权限修改失败：%1。","admin_user_frozen":"冻结","admin_user_frozen_set":"已修改用户冻结状态。","admin_user_frozen_failed":"用户冻结状态修改失败：%1。","admin_operation":"操作","admin_user_set_password":"设置密码","admin_user_password_ok":"密码已修改。","admin_user_password_failed":"密码修改失败：%1。","admin_user_set_avatar":"设置头像","admin_user_check_gallery":"查看用户图片库","admin_delete":"删除","admin_user_delete_ok":"用户已删除。","admin_user_delete_failed":"用户删除失败：%1。","admin_user_delete_selected":"删除已选用户","admin_user_delete_selected_ok":"所选用户已删除。","admin_user_delete_selected_failed":"所选用户删除失败：%1。","admin_user_add":"添加用户","admin_code_code":"邀请码","admin_code_times":"可用次数","admin_code_set_times":"设置可用次数","admin_code_delete_selected":"删除已选邀请码","admin_code_add":"添加邀请码","admin_code_fetch_failed":"邀请码列表加载失败：%1。","admin_code_delete_ok":"已删除邀请码。","admin_code_delete_failed":"邀请码删除失败：%1。","admin_times_set_ok":"已更新可用次数。","admin_times_set_failed":"可用次数更新失败：%1。","paginator_first_page":"第一页","paginator_last_page":"最后一页","paginator_previous_page":"上一页","paginator_next_page":"下一页","paginator_per_page":"每页条目：","paginator_position_none":"无项目","paginator_position_zero":"当前列表无项目，共有%1个项目","paginator_position":"第%1到%2个项目，共%3个项目","default_prompt_title":"输入一个值","default_prompt_label":"值","default_prompt_placeholder":"在此输入值","default_prompt_yes":"确定","default_prompt_no":"取消","set_password_prompt_title":"设置用户密码","set_password_prompt_label":"新密码","set_password_prompt_placeholder":"在此输入新密码","set_password_prompt_yes":"设置","set_password_prompt_no":"取消","delete_user_confirm_title":"删除用户","delete_user_confirm_word":"你确定要删除这个用户吗？","delete_user_confirm_yes":"删除","delete_user_confirm_no":"取消","delete_users_confirm_title":"删除已选用户","delete_users_confirm_word":"你确定要删除这些用户吗？","delete_users_confirm_yes":"删除","delete_users_confirm_no":"取消","default_choice_title":"选择一个值","default_choice_word":"请从下面两个值中选择一个","default_choice_right":"右","default_choice_left":"左","delete_user_choice_title":"处理用户图片","delete_user_choice_word":"如何处理该用户上传的图片？","delete_user_choice_right":"归入此帐号","delete_user_choice_left":"删除","delete_users_choice_title":"处理用户图片","delete_users_choice_word":"如何处理所选用户上传的图片？","delete_users_choice_right":"归入此帐号","delete_users_choice_left":"删除","add_user_title":"添加用户","add_user_username":"用户名","add_user_password":"密码","add_user_privileged":"赋予高级功能权限","add_user_error_user_exist":"用户已存在","add_user_cancel":"取消","add_user_submit":"添加","add_user_success_msg":"已添加用户%1。","add_user_error_msg":"用户添加失败：%1。","add_code_title":"添加邀请码","add_code_code":"邀请代码","add_code_times":"可用次数","add_code_error_code_exist":"该邀请码已存在","add_code_cancel":"取消","add_code_submit":"添加","add_code_success_msg":"已添加邀请码%1。","add_code_error_msg":"邀请码添加失败：%1。","code_times_prompt_title":"设置可用次数","code_times_prompt_label":"可用次数","code_times_prompt_placeholder":"输入一个数字","code_times_prompt_yes":"保存","code_times_prompt_no":"取消","delete_code_confirm_title":"删除邀请码","delete_code_confirm_word":"确实要删除这个邀请码吗？","delete_code_confirm_yes":"删除","delete_code_confirm_no":"取消","not_found_title":"Not found","not_found_word":"此页面没有内容。","not_found_back":"返回主页","format_pref_title":"图像格式偏好设置","format_pref_note_title":"提示：","format_pref_note_content":"你可以在这里设置你对不同格式图像的偏好。默认情况下服务器会以你浏览器所支持，且文件大小最小的格式提供图片，但这需要CPU进行更多运算以显示图片。一般情况下解码时间的差异可以忽略不计，但更小的文件可以显著提高加载速度，因此我们推荐你使用默认设置。如果你正在使用一个低性能设备，或你十分关心设备的续航时间，你可以在此手动设置你对各种格式的偏好，我们在提供图片时会优先考虑你设置的顺序。","format_pref_support_status":"你浏览器对各种图片格式的支持：","format_pref_support_status_detecting":"正在检测……","format_pref_support_status_supported":"支持","format_pref_support_status_not_supported":"不支持","format_pref_support_status_jpeg_png":"所有浏览器都支持PNG和JPEG格式。","format_pref_drag_hint":"拖拽以改变顺序：","format_pref_cancel":"取消","format_pref_reset":"重置","format_pref_save":"保存","format_pref_save_done":"偏好已保存。","format_pref_reset_done":"偏好已重置。","about_title":"关于","about_content":"Chromatic是一个专注于优化Web访问体验的图片存储平台。","about_privacy":"隐私","about_privacy_content":"我们注重对你的隐私保护，仅收集最低限度的必要数据。在你浏览图片时，我们会匿名统计图片的访问次数，并依此决定我们是否应该使用更多服务器资源进一步优化浏览体验。如果你设置了图片格式偏好，则每当你请求图片（包括在其他网站加载来自本平台的图片）时，都会向服务器发送一个Cookie以告知你的偏好。此Cookie不会被用作其他用途。","about_based_on":"鸣谢","about_based_content":"Chromatic的诞生离不开许许多多开源项目的支持。","about_license_other":"其他许可","info_main":"主页","info_about":"关于","title_about":"关于","title_admin":"管理","title_gallery":"图片库","title_gallery_me":"我的图片库","title_login":"登录","title_register":"注册","title_not_found":"未知页面","title_upload":"上传图片","title_uploading":"正在上传，%1个文件已上传","title_uploading_error":"正在上传，%1个文件已上传，%2个文件上传失败","title_uploaded":"%1个文件上传成功","title_uploaded_error":"%1个文件上传成功，%2个文件上传失败","time_year":"y年","time_year_post":"%1","time_month":"y年MMM","time_month_post":"%1","time_week":"y年第w周","time_week_post":"%1","time_day":"mediumDate","time_day_post":"%1","0000":"成功","0001":"密码强度过弱","0002":"用户已经存在","0003":"邀请码无效","0004":"用户名或密码不正确","0005":"所选用户不存在","0006":"指定的邀请码已经存在","0007":"指定的邀请码不存在","0008":"请求不合法","0009":"指定的图片不存在","0010":"图片文件已损坏，或不支持此格式","0011":"图片编码失败","0012":"原始图片不存在","0013":"请求缺少认证代码","0014":"认证代码已过期","0015":"权限不足","http_error":"HTTP %1","net_error":"网络错误","action_retry":"重试","login_expired":"你的登录信息已过期。请重新登录。","other":"(!缺失!)"},"zh-TW":{"9999":"未知錯誤","main_subtitle":"分享你的圖片。為Web訪問最佳化。","main_register":"註冊","main_login":"登入","language_switch":"切換語言","header_admin":"管理界面","header_upload":"上傳","header_upload_frozen":"你的帳號已被停用。","header_change_avatar":"更換頭像","header_change_password":"更改密碼","header_logout":"退出登入","header_image_pref":"圖像格式偏好","header_gallery":"圖片庫","login_title":"登入","login_username":"使用者名稱","login_password":"密碼","login_action_login":"登入","login_action_register":"註冊新帳號","login_success_message":"登入成功。","login_failed_message":"登入失敗：%1。","register_title":"註冊","register_username":"使用者名稱","register_password":"密碼","register_password_repeat":"重複密碼","register_password_see":"顯示密碼","register_password_hide":"隱藏密碼","register_code":"邀請碼","register_hint_password":"密碼至少8位長，須同時包含數字及大小寫字母","register_error_user_exist":"用戶已經存在","register_error_password_weak":"密碼強度太弱","register_error_password_mismatch":"兩次輸入的密碼不一致","register_action_login":"登入已有帳號","register_action_register":"註冊","guard_need_login_message":"你必須登入才可瀏覽此界面。","gallery_broken_image":"圖片不可用","gallery_loading":"正在載入……","gallery_tag_search":"僅顯示特定標籤的圖片","gallery_tag_placeholder":"輸入標籤","gallery_tag_failed_message":"標籤載入失敗：%1。","gallery_tag_empty":"（空標籤）","gallery_group_label":"分組依據：","gallery_group_time":"時間","gallery_group_tag":"標籤","gallery_group_time_label":"分組時長：","gallery_group_time_day":"天","gallery_group_time_week":"周","gallery_group_time_month":"月","gallery_group_time_year":"年","gallery_select_all_typed":"全選本組","gallery_deselect_all_typed":"取消選擇本組","gallery_reverse_all_typed":"反選本組","gallery_action_edit":"編輯所選圖片","gallery_action_code":"獲取所選圖片的發布代碼","gallery_action_delete":"刪除所選圖片","gallery_action_select_all":"選擇當前所有圖片","gallery_action_select_reverse":"反選所有圖片","gallery_action_done":"完成","gallery_overlay_action_info":"圖片訊息","gallery_overlay_action_open":"在新標籤頁內打開圖片","gallery_overlay_action_edit":"編輯此圖片訊息","gallery_overlay_action_code":"獲取此圖片的發布代碼","gallery_overlay_action_delete":"刪除此圖片","gallery_overlay_action_close":"回到列表","gallery_fetch_failed":"圖片列表載入失敗：%1。","gallery_empty":"你還沒有上傳圖片。","gallery_empty_other":"無圖片。","gallery_empty_upload":"上傳","upload_minimize":"最小化","upload_expand":"還原","upload_close":"關閉","upload_title_file_plural_0":"尚無文件","upload_title_file_plural_1":"1個文件","upload_title_file_plural_other":"個文件","upload_title_idle":"上傳","upload_title_select_files_p1":"已選擇","upload_title_select_files_p2":"","upload_title_uploading_fine_p1":"正在上傳，","upload_title_uploading_fine_p2":"，","upload_title_uploading_fine_p3":"已上傳完畢。","upload_title_uploading_some_error_p1":"正在上傳，","upload_title_uploading_some_error_p2":"，","upload_title_uploading_some_error_p3":"已上傳完畢，","upload_title_uploading_some_error_p4":"上傳失敗。","upload_title_uploaded_fine":"上傳完畢，全部文件上傳成功。","upload_title_uploaded_some_error_p1":"上傳完畢，","upload_title_uploaded_some_error_p2":"上傳成功，","upload_title_uploaded_some_error_p3":"上傳失敗。","upload_drop_file_pre":"將文件拖拽到此處，或","upload_drop_file_picker":"選擇文件","upload_drop_file_post":"以上傳。","upload_drop_file_release":"鬆開滑鼠即可上傳","upload_file_name_unknown":"（未知檔案名）","upload_file_type_unknown":"（未知格式）","upload_submit_no_valid":"你選擇的文件裡沒有圖片。","upload_preview_type_header":"顯示模式：","upload_preview_type_grid":"網格","upload_preview_type_list":"列表","upload_preview_limit_height":"限制預覽高度","upload_preview_title":"圖片預覽","upload_info_form_title":"設置","upload_info_tag_header":"圖片標籤","upload_info_tag_header_help":"標籤是用來歸類圖像的主要方式","upload_info_tag_header_placeholder":"在此輸入標籤，或留空以使用空標籤","upload_info_tag_header_hint":"（默認：創建新標籤）","upload_info_allow_origins":"可訪問網站","upload_info_allow_origins_help":"瀏覽者僅能從這些網站訪問你的圖片","upload_info_allow_origins_placeholder":"在此輸入域名，使用逗號或回車分隔","upload_info_allow_origins_any":"（任何網站）","upload_info_allow_origins_none":"（直接打開）","upload_info_allow_origins_exact":"（精確匹配）","upload_info_allow_origins_wildcard":"（允許子站）","upload_info_allow_origins_bad":"（當前輸入不是一個有效域名）","upload_info_allow_origins_exist":"（允許列表已包含此域名）","upload_failed_info":"上傳失敗：%1","upload_operation_reset":"重設","upload_operation_submit":"上傳","upload_advanced_button":"高級上傳","upload_advanced_title":"高級上傳","upload_advanced_warning_head":"警告：","upload_advanced_warning_text":"高級上傳允許你手動上傳不同格式的同一張圖片，並直接將上傳的文件提供給用戶。服務端不會對上傳的文件進行任何校驗，因此本功能僅面向高級用戶。在操作時請小心。","upload_advanced_file_title":"上傳文件","upload_advanced_select_file":"選擇文件","upload_advanced_selected":"重新選擇","upload_advanced_status_not_selected":"尚未選擇文件","upload_advanced_status_before":"檔案大小：","upload_advanced_status_after":"。","upload_advanced_info_title":"設置","upload_advanced_operation_cancel":"取消","upload_advanced_operation_upload":"上傳","upload_advanced_operation_uploading":"正在上傳","upload_advanced_operation_uploaded":"關閉","upload_advanced_operation_exit":"退出","upload_advanced_failed_message":"上傳失敗： %1。","upload_advanced_success_message":"上傳成功","upload_advanced_progress":"上傳進度","edit_images_title":"編輯圖片","edit_images_tab_tag":"標籤","edit_images_title_tag":"更改圖片標籤","edit_images_tab_origins":"可訪問網站","edit_images_title_origins":"更改圖片可訪問網站","edit_images_result_success":"圖片編輯成功。","edit_images_result_failed":"圖片編輯失敗：%1。","dialog_cancel":"取消","dialog_submit":"確定","default_confirm_title":"確認","default_confirm_word":"確定要執行動作嗎？","default_confirm_yes":"確定","default_confirm_no":"取消","delete_select_confirm_title":"刪除圖片","delete_select_confirm_word":"確定要刪除選擇的圖片嗎？","delete_select_confirm_yes":"刪除","delete_select_confirm_no":"取消","delete_this_confirm_title":"刪除此圖片","delete_this_confirm_word":"確定要刪除這張圖片嗎？","delete_this_confirm_yes":"刪除","delete_this_confirm_no":"取消","upload_confirm_title":"中止上傳並退出","upload_confirm_word":"確定要退出嗎？部分文件可能不會被上傳。","upload_confirm_yes":"退出","upload_confirm_no":"取消","delete_images_result_success":"圖片已刪除。","delete_images_result_failed":"圖片刪除失敗：%1。","generate_code_title":"生成發布代碼","generate_code_type":"代碼類型","generate_code_type_label":"選擇一個代碼類型","generate_type_html":"HTML","generate_type_bbcode":"BBCode","generate_type_url":"連結","generate_type_custom":"自訂","generate_custom_template":"模板","generate_custom_template_placeholder":"每張圖片的代碼模板","generate_custom_template_hint":"請使用%url%標註放置圖片連結的位置","generate_custom_separator":"分隔內容","generate_custom_separator_placeholder":"置於圖片間的代碼","generate_custom_separator_hint":"分隔代碼將置於每兩張圖片代碼的中間","generate_result_copy":"複製","generate_result_copied":"代碼已複製","generate_code_done":"完成","generate_sort_title":"排序圖片","generate_sort_reverse":"反序","info_title":"圖片訊息","info_user":"所有者","info_tag":"標籤","info_upload_time":"上傳時間","info_view":"瀏覽量","info_origins":"允許訪問的站點","info_formats":"可用格式","info_formats_available":"此格式可用","info_formats_encoding":"此格式正在轉檔，即將可用","info_done":"關閉","change_password_title":"更改密碼","change_password_old":"舊密碼","change_password_new":"新密碼","change_password_cancel":"取消","change_password_submit":"更改","change_password_failed":"更改密碼失敗：%1。","change_password_succeed":"密碼已更改。請重新登入。","change_avatar_title":"更換頭像","change_avatar_title_pick_file":"第一步：請選擇一張圖片","change_avatar_file_selector":"選擇圖片","change_avatar_file_bad":"圖片載入失敗。請確認這是一個圖片文件。","change_avatar_title_crop":"第二步：裁剪圖片","change_avatar_preview_no_file":"請先選擇一張圖片，進行裁剪。","change_avatar_preview":"頭像預覽","change_avatar_success":"頭像已更換。","change_avatar_failed":"頭像更換失敗：%1","change_avatar_cancel":"取消","change_avatar_submit":"保存","admin_user":"用戶","admin_code":"邀請碼","admin_user_search":"僅顯示使用者名稱包含關鍵字的用戶","admin_user_search_placeholder":"輸入關鍵字","admin_user_fetch_failed":"用戶列表獲取失敗：%1。","admin_user_username":"使用者名稱","admin_user_privileged":"進階功能權限","admin_user_privileged_set":"已修改用戶權限。","admin_user_privileged_failed":"用戶權限修改失敗：%1。","admin_user_frozen":"凍結","admin_user_frozen_set":"已修改用戶凍結狀態。","admin_user_frozen_failed":"用戶凍結狀態修改失敗：%1。","admin_operation":"操作","admin_user_set_password":"設置密碼","admin_user_password_ok":"密碼已修改。","admin_user_password_failed":"密碼修改失敗：%1。","admin_user_set_avatar":"設置頭像","admin_user_check_gallery":"查看用戶圖片庫","admin_delete":"刪除","admin_user_delete_ok":"用戶已刪除。","admin_user_delete_failed":"用戶刪除失敗：%1。","admin_user_delete_selected":"刪除已選用戶","admin_user_delete_selected_ok":"所選用戶已刪除。","admin_user_delete_selected_failed":"所選用戶刪除失敗：%1。","admin_user_add":"添加用戶","admin_code_code":"邀請碼","admin_code_times":"可用次數","admin_code_set_times":"設置可用次數","admin_code_delete_selected":"刪除已選邀請碼","admin_code_add":"添加邀請碼","admin_code_fetch_failed":"邀請碼列表載入失敗：%1。","admin_code_delete_ok":"已刪除邀請碼。","admin_code_delete_failed":"邀請碼刪除失敗：%1。","admin_times_set_ok":"已更新可用次數。","admin_times_set_failed":"可用次數更新失敗：%1。","paginator_first_page":"第一頁","paginator_last_page":"最後一頁","paginator_previous_page":"上一頁","paginator_next_page":"下一頁","paginator_per_page":"每頁條目：","paginator_position_none":"無項目","paginator_position_zero":"當前列表無項目，共有%1個項目","paginator_position":"第%1到%2個項目，共%3個項目","default_prompt_title":"輸入一個值","default_prompt_label":"值","default_prompt_placeholder":"在此輸入值","default_prompt_yes":"確定","default_prompt_no":"取消","set_password_prompt_title":"設置用戶密碼","set_password_prompt_label":"新密碼","set_password_prompt_placeholder":"在此輸入新密碼","set_password_prompt_yes":"設置","set_password_prompt_no":"取消","delete_user_confirm_title":"刪除用戶","delete_user_confirm_word":"你確定要刪除這個用戶嗎？","delete_user_confirm_yes":"刪除","delete_user_confirm_no":"取消","delete_users_confirm_title":"刪除已選用戶","delete_users_confirm_word":"你確定要刪除這些用戶嗎？","delete_users_confirm_yes":"刪除","delete_users_confirm_no":"取消","default_choice_title":"選擇一個值","default_choice_word":"請從下面兩個值中選擇一個","default_choice_right":"右","default_choice_left":"左","delete_user_choice_title":"處理用戶圖片","delete_user_choice_word":"如何處理該用戶上傳的圖片？","delete_user_choice_right":"歸入此帳號","delete_user_choice_left":"刪除","delete_users_choice_title":"處理用戶圖片","delete_users_choice_word":"如何處理所選用戶上傳的圖片？","delete_users_choice_right":"歸入此帳號","delete_users_choice_left":"刪除","add_user_title":"添加用戶","add_user_username":"使用者名稱","add_user_password":"密碼","add_user_privileged":"賦予進階功能權限","add_user_error_user_exist":"用戶已存在","add_user_cancel":"取消","add_user_submit":"添加","add_user_success_msg":"已添加用戶%1。","add_user_error_msg":"用戶添加失敗：%1。","add_code_title":"添加邀請碼","add_code_code":"邀請代碼","add_code_times":"可用次數","add_code_error_code_exist":"該邀請碼已存在","add_code_cancel":"取消","add_code_submit":"添加","add_code_success_msg":"已添加邀請碼%1。","add_code_error_msg":"邀請碼添加失敗：%1。","code_times_prompt_title":"設置可用次數","code_times_prompt_label":"可用次數","code_times_prompt_placeholder":"輸入一個數字","code_times_prompt_yes":"保存","code_times_prompt_no":"取消","delete_code_confirm_title":"刪除邀請碼","delete_code_confirm_word":"確定要刪除這個邀請碼嗎？","delete_code_confirm_yes":"刪除","delete_code_confirm_no":"取消","not_found_title":"Not found","not_found_word":"此頁面沒有內容。","not_found_back":"返回首頁","format_pref_title":"圖像格式偏好設置","format_pref_note_title":"提示：","format_pref_note_content":"你可以在這裡設置你對不同格式圖像的偏好。默認情況下伺服器會以你瀏覽器所支持，且檔案大小最小的格式提供圖片，但這需要CPU進行更多運算以顯示圖片。一般情況下解碼時間的差異可以忽略不計，但更小的文件可以顯著提高載入速度，因此我們推薦你使用默認設置。如果你正在使用一個低性能設備，或你十分關心設備的續航時間，你可以在此手動設置你對各種格式的偏好，我們在提供圖片時會優先考慮你設置的順序。","format_pref_support_status":"你瀏覽器對各種圖片格式的支持：","format_pref_support_status_detecting":"正在檢測……","format_pref_support_status_supported":"支持","format_pref_support_status_not_supported":"不支持","format_pref_support_status_jpeg_png":"所有瀏覽器都支持PNG和JPEG格式。","format_pref_drag_hint":"拖拽以改變順序：","format_pref_cancel":"取消","format_pref_reset":"重設","format_pref_save":"保存","format_pref_save_done":"偏好已保存。","format_pref_reset_done":"偏好已重設。","about_title":"關於","about_content":"Chromatic是一個專注於最佳化Web訪問體驗的圖片儲存平台。","about_privacy":"隱私","about_privacy_content":"我們注重對你的隱私保護，僅收集最低限度的必要數據。在你瀏覽圖片時，我們會匿名統計圖片的訪問次數，並依此決定我們是否應該使用更多伺服器資源進一步最佳化瀏覽體驗。如果你設置了圖片格式偏好，則每當你請求圖片（包括在其他網站載入來自本平台的圖片）時，都會向伺服器發送一個Cookie以告知你的偏好。此Cookie不會被用作其他用途。","about_based_on":"鳴謝","about_based_content":"Chromatic的誕生離不開許許多多開源項目的支持。","about_license_other":"其他許可","info_main":"首頁","info_about":"關於","title_about":"關於","title_admin":"管理","title_gallery":"圖片庫","title_gallery_me":"我的圖片庫","title_login":"登入","title_register":"註冊","title_not_found":"未知頁面","title_upload":"上傳圖片","title_uploading":"正在上傳，%1個文件已上傳","title_uploading_error":"正在上傳，%1個文件已上傳，%2個文件上傳失敗","title_uploaded":"%1個文件上傳成功","title_uploaded_error":"%1個文件上傳成功，%2個文件上傳失敗","time_year":"y年","time_year_post":"%1","time_month":"y年MMM","time_month_post":"%1","time_week":"y年第w周","time_week_post":"%1","time_day":"mediumDate","time_day_post":"%1","0000":"成功","0001":"密碼強度太弱","0002":"用戶已經存在","0003":"邀請碼無效","0004":"使用者名稱或密碼不正確","0005":"所選用戶不存在","0006":"指定的邀請碼已經存在","0007":"指定的邀請碼不存在","0008":"請求不合法","0009":"指定的圖片不存在","0010":"圖片文件已損壞，或不支持此格式","0011":"圖片編碼失敗","0012":"原始圖片不存在","0013":"請求缺少認證代碼","0014":"認證代碼已過期","0015":"權限不足","http_error":"HTTP %1","net_error":"網路錯誤","action_retry":"重試","login_expired":"你的登入訊息已過期。請重新登入。","other":"(!缺失!)"}}`;
export const TransTable: { [key: string]: { [key: string]: string } } = JSON.parse(langJSON);

TransTable.zh = TransTable['zh-CN'];
TransTable['zh-HK'] = TransTable['zh-TW'];
TransTable['zh-MO'] = TransTable['zh-TW'];
TransTable['zh-Hant'] = TransTable['zh-TW'];

